/** Synthetic-only parity adapter. It never provides provider fallback or real device verification. */
import {APIError} from '../api/client';
import {operationID} from '../api/id';
import {categories,localMonth} from '../api/parity';
import type {Controls, SavedBill, Reminder, Mandate, MoneyRequest, RequestDetail, Draft, Upload, FundingAccount, Identity} from '../api/parity';
import type {Method, RequestOptions, Payment, Quote} from '../api/types';
import type {State} from './transport';
const now=()=>new Date().toISOString();
const future=(days:number)=>new Date(Date.now()+days*86400000).toISOString();
const id=(prefix:string)=>`${prefix}_review_${operationID().replaceAll('-','')}`;
const recipient='usr_review_tunde_02';
function error(message:string,status=409):never {throw new APIError(status,'review_validation',message)}
const minor=(value:unknown):bigint=>{if(typeof value!=='string'||!/^(0|[1-9][0-9]{0,15})$/.test(value)||BigInt(value)>9000000000000000n)error('Use a valid minor-unit amount.',400);return BigInt(value as string)};
const text=(value:unknown,max=150):string=>{if(typeof value!=='string'||!value.trim()||value.length>max)error('A bounded value is required.',400);return value as string};
interface ReviewRequest extends RequestDetail{created_at:string;key?:string;fingerprint?:string}
export interface ParityState {
 controls:Controls;saved:SavedBill[];reminders:Reminder[];mandates:Mandate[];
 requests:ReviewRequest[];links:Record<string,{request:string;share:string;amount:string}>;
 annotations:Record<string,{category:string;note:string;excluded:boolean}>;
 budgets:Record<string,Record<string,string>>;draft:Draft;uploads:Upload[];
 funding:FundingAccount;watches:string[];emailChange?:{id:string;email:string};
 events:Record<string,{action:string;created_at:string}[]>;
}
function parity(s:State):ParityState {
 if(!s.parity){const rid='req_review_incoming_001';s.parity={controls:{handle:'amina',discoverable:false,frozen:false,per_payment_minor:'10000000',daily_minor:'50000000',daily_remaining_minor:'50000000'},saved:[],reminders:[],mandates:[],requests:[{id:rid,owner_id:recipient,requester_name:'Tunde Adeyemi · synthetic',memo:'Shared household bill · synthetic',amount_minor:'300000',currency:'NGN',expires_at:future(7),status:'open',created_at:now(),shares:[{id:'share_review_001',payer_id:s.user.id,name:s.user.name,amount_minor:'300000',received_minor:'0',status:'open'}]}],links:{},annotations:{},budgets:{},draft:{version:0,draft:null},uploads:[],funding:{state:'not_created',configured:true},watches:[],events:{}}}
 return s.parity;
}
function reauthenticate(body:Record<string,unknown>){if(body.password!=='Review-only-2026')error('Use the displayed synthetic review password.',401)}
function notice(s:State,workflow:string,subject:string,reference:string){s.notices.unshift({id:id('notice'),workflow,subject,reference,created_at:now(),read:false})}
function checkedRequest(p:ParityState,rid:string):ReviewRequest {const r=p.requests.find(x=>x.id===rid);if(!r)error('Request not found.',404);if(r.status!=='open'||Date.parse(r.expires_at)<=Date.now())error('The request is closed or expired.');return r}
/** Financial effect stays in the original review ledger; this only enforces linked-request state. */
export function beforeReviewPayment(s:State,q:Quote){const p=parity(s);if(p.controls.frozen)error('The synthetic account is frozen.',403);if(minor(q.total_minor)>minor(p.controls.per_payment_minor))error('Personal payment limit exceeded.');const link=p.links[q.id];if(!link)return;const r=checkedRequest(p,link.request),share=r.shares.find(x=>x.id===link.share&&x.payer_id===s.user.id);if(!share||share.status!=='open'||minor(link.amount)>minor(share.amount_minor)-minor(share.received_minor))error('The request share changed. Obtain a new quote.');}
export function afterReviewPayment(s:State,payment:Payment){const p=parity(s),link=p.links[payment.quote_id];if(!link||payment.status!=='succeeded')return;const r=p.requests.find(x=>x.id===link.request)!,share=r.shares.find(x=>x.id===link.share)!;share.received_minor=(minor(share.received_minor)+minor(link.amount)).toString();if(share.received_minor===share.amount_minor)share.status='paid';if(r.shares.every(x=>x.status==='paid'))r.status='completed';delete p.links[payment.quote_id];}
export function reviewParity(s:State,method:Method,url:URL,options:RequestOptions):{handled:boolean;value?:unknown} {
 const path=url.pathname,p=parity(s),b=(options.body||{}) as Record<string,unknown>,part=path.split('/'),last=part.at(-1)!;
 const yes=(value?:unknown)=>({handled:true,value});
 if(path==='/v1/me/capabilities')return yes({version:1,currency:'NGN',tier:s.user.tier,account_status:s.user.status,email_verified:s.user.email_verified,controls:p.controls,features:{payments:p.controls.frozen?'restricted':s.user.tier<1?'verification_required':'eligible',private_uploads:'eligible',funding_accounts:'eligible',recipient_lookup:'eligible',reminders:'eligible',scheduled_internal_transfers:'eligible',money_requests:'eligible',insights:'eligible',passkeys:'not_offered',cards:'not_offered',external_autopay:'not_offered'},checked_at:now(),synthetic:true,limit_day_timezone:'UTC'});
 if(path==='/v1/me/controls'){if(method==='PATCH'){reauthenticate(b);const per=minor(b.per_payment_minor),daily=minor(b.daily_minor);if(per<=0n||daily<per||per>10000000n||daily>50000000n)error('Personal limits must fit the synthetic account policy.');const handle=String(b.handle||'');if(handle&&!/^[a-z][a-z0-9_]{3,23}$/.test(handle))error('Invalid handle.',400);if(['tunde','support','admin'].includes(handle))error('Handle is unavailable.');p.controls={...p.controls,handle,discoverable:b.discoverable===true,per_payment_minor:per.toString(),daily_minor:daily.toString(),daily_remaining_minor:daily.toString()};notice(s,'security-personal-controls-changed','Personal security controls changed',s.user.id);return yes({status:'accepted'})}return yes(p.controls)}
 if(path==='/v1/me/freeze'){reauthenticate(b);p.controls.frozen=b.frozen===true;s.devices.filter(x=>!x.current).forEach(x=>x.revoked=true);return yes({status:'accepted'})}
 if(path==='/v1/auth/logout-all'){s.signedIn=false;s.devices.forEach(x=>x.revoked=true);return yes({status:'accepted'})}
 if(path==='/v1/auth/history')return yes([{action:'session.created',created_at:now()}]);
 if(path==='/v1/passkeys')return yes([]);
 if(path.startsWith('/v1/passkeys/')||path.startsWith('/v1/auth/passkeys/'))error('Device-authentication tests require the API-connected application.',503);
 if(path==='/v1/recipients/lookup'){if(url.searchParams.get('handle')?.replace(/^@/,'')!=='tunde')error('No eligible discoverable recipient matched that exact handle.',404);return yes({id:recipient,name:'Tunde Adeyemi · synthetic',handle:'tunde',name_kind:'display_name'})}
 if(path==='/v1/payments/lookup'){const key=url.searchParams.get('idempotency_key'),qid=url.searchParams.get('quote_id');const payment=s.payments.find(x=>(!key||x.id===s.idempotency[key])&&(!qid||x.quote_id===qid));return yes({found:!!payment,...(payment?{payment}:{}),conclusive_failure:false})}
 if(/^\/v1\/payments\/[^/]+\/(timeline|draft|annotation)$/.test(path)){
  const payment=s.payments.find(x=>x.id===part[3]);if(!payment)error('Payment not found.',404);const q=s.quotes[payment.quote_id];
  if(last==='timeline')return yes({payment,hold_state:payment.kind==='internal'?'':payment.status==='pending'?'active':payment.status==='succeeded'?'captured':'released',hold_minor:payment.kind==='internal'?'0':payment.total_minor,events:[{type:'request_received',at:payment.created_at},{type:'synthetic_outcome',status:payment.status,at:payment.updated_at}],next_action:payment.status==='succeeded'?'Confirmed outcome.':payment.status==='failed'?'Confirmed unsuccessful. No success receipt.':'Check the original operation; do not submit a replacement.'});
  if(last==='annotation'){if(method==='PATCH'){if(!categories.includes(String(b.category)))error('Unknown category.',400);p.annotations[payment.id]={category:String(b.category),note:String(b.note||''),excluded:b.excluded===true};return yes({status:'accepted'})}return yes(p.annotations[payment.id]||{category:payment.kind==='bill'?'other':'transfers',note:'',excluded:false})}
  if(payment.direction!=='outgoing')error('Only outgoing payments can prepare a new draft.');return yes({kind:payment.kind,amount_minor:payment.amount_minor,currency:'NGN',narration:q?.narration||'Repeat synthetic payment',destination:q?.destination||{user_id:recipient,account_name:'Synthetic recipient',bank_code:'999',account_number:'1234567890'},requires_new_quote:true});
 }
 if(/^\/v1\/beneficiaries\/[^/]+\/favourite$/.test(path)){const v=s.beneficiaries.find(x=>x.id===part[3]);if(!v)error('Beneficiary not found.',404);v.favourite=b.favourite===true;return yes({status:'accepted'})}
 if(path==='/v1/saved-bills'||/^\/v1\/saved-bills\/[^/]+$/.test(path)){
  if(method==='GET')return yes(p.saved);
  if(method==='DELETE'){p.saved=p.saved.filter(x=>x.id!==last);p.reminders.filter(x=>x.bill_id===last).forEach(x=>x.status='cancelled');return yes()}
  const record:SavedBill={id:method==='POST'?id('bill'):last,label:text(b.label,80),product_id:text(b.product_id,100),customer_id:text(b.customer_id,100),amount_minor:minor(b.amount_minor).toString(),currency:'NGN',favourite:b.favourite===true};if(method==='PATCH'&&!p.saved.some(x=>x.id===last))error('Saved bill not found.',404);p.saved=[record,...p.saved.filter(x=>x.id!==record.id)];return yes({id:record.id});
 }
 if(path==='/v1/bills/token-archive')return yes(s.payments.filter(x=>x.kind==='bill'&&x.status==='succeeded').map(x=>({id:x.id,amount_minor:x.amount_minor,currency:x.currency,fulfilment_status:x.fulfilment_status,created_at:x.created_at})));
 if(path==='/v1/bills/availability')return yes(['review-electricity','review-airtime','review-data-5gb','review-tv','review-internet','review-other'].map(product_id=>({product_id,state:'unknown',observed_at:now(),watching:p.watches.includes(product_id)})));
 if(path==='/v1/bills/watch'){const product=text(b.product_id,100);p.watches=b.watching===true?[...new Set([...p.watches,product])]:p.watches.filter(x=>x!==product);return yes({status:'accepted'})}
 if(path==='/v1/reminders'){if(method==='GET')return yes(p.reminders);const cadence=String(b.cadence);if(!['once','weekly','monthly'].includes(cadence)||Date.parse(String(b.due_at))<=Date.now())error('Choose a future reminder and supported cadence.');const v:Reminder={id:id('rem'),title:text(b.title,100),amount_minor:minor(b.amount_minor).toString(),bill_id:String(b.bill_id||''),due_at:String(b.due_at),ends_at:b.ends_at?String(b.ends_at):undefined,cadence,status:'active',version:1};p.reminders.unshift(v);return yes({id:v.id})}
 if(/^\/v1\/reminders\/[^/]+$/.test(path)){const r=p.reminders.find(x=>x.id===part[3]);if(!r)error('Reminder not found.',404);if(r.version!==b.version)error('Reminder changed; refresh it.');if(!['active','paused','cancelled'].includes(String(b.status)))error('Invalid state.',400);r.status=String(b.status);r.version++;return yes({status:'accepted'})}
 if(path==='/v1/mandates'){if(method==='GET')return yes(p.mandates);if(b.pin!=='123456')error('Use the synthetic transaction PIN.',401);const q=s.quotes[String(b.quote_id)];if(!q||q.kind!=='internal'||q.used||Date.parse(q.expires_at)<=Date.now())error('Obtain a fresh internal-transfer quote.');if(b.consent!==true)error('Explicit mandate consent required.');const max=minor(b.max_debit_minor),total=minor(b.max_total_minor);if(max<minor(q.total_minor)||total<max)error('Mandate amount caps are too small.');const v:Mandate={id:id('mandate'),title:text(b.title,100),cadence:String(b.cadence),next_at:String(b.first_at),ends_at:String(b.ends_at),max_debit_minor:max.toString(),max_total_minor:total.toString(),max_occurrences:Number(b.max_occurrences),occurrences:0,committed_total_minor:'0',status:'active',version:1};p.mandates.unshift(v);return yes({id:v.id,synthetic:true})}
 if(/^\/v1\/mandates\/[^/]+(?:\/history)?$/.test(path)){const m=p.mandates.find(x=>x.id===part[3]);if(!m)error('Mandate not found.',404);if(last==='history')return yes([]);if(m.version!==b.version)error('Mandate changed.');m.status=String(b.status);m.version++;return yes({status:'accepted'})}
 if(path==='/v1/money-requests'){
  if(method==='GET')return yes(p.requests.map(r=>({...r,received_minor:r.shares.reduce((sum,x)=>sum+minor(x.received_minor),0n).toString(),direction:r.owner_id===s.user.id?'outgoing':'incoming'})));
  const key=options.idempotencyKey||'';if(key.length<16)error('A persistent request key is required.',400);const fingerprint=JSON.stringify(b),prior=p.requests.find(x=>x.key===key);if(prior){if(prior.fingerprint!==fingerprint)error('This key belongs to another request.');return yes({id:prior.id})}
  const amount=minor(b.amount_minor),shares=b.shares as {payer_id:string;amount_minor:string}[];if(!Array.isArray(shares)||!shares.length||shares.length>20||shares.reduce((sum,x)=>sum+minor(x.amount_minor),0n)!==amount||new Set(shares.map(x=>x.payer_id)).size!==shares.length||shares.some(x=>x.payer_id===s.user.id||minor(x.amount_minor)<=0n))error('Shares must be positive, unique, and sum exactly to the total.',400);
  const r:ReviewRequest={id:id('req'),owner_id:s.user.id,requester_name:s.user.name,memo:text(b.memo,140),amount_minor:amount.toString(),currency:'NGN',expires_at:String(b.expires_at),status:'open',created_at:now(),key,fingerprint,shares:shares.map(x=>({...x,id:id('share'),name:'Tunde Adeyemi · synthetic',received_minor:'0',status:'open'}))};if(Date.parse(r.expires_at)<=Date.now())error('Choose a future expiry.');p.requests.unshift(r);return yes({id:r.id});
 }
 if(/^\/v1\/money-requests\/[^/]+(?:\/(action|quote))?$/.test(path)){
  const r=p.requests.find(x=>x.id===part[3]);if(!r)error('Request not found.',404);if(method==='GET')return yes({...r,shares:r.owner_id===s.user.id?r.shares:r.shares.filter(x=>x.payer_id===s.user.id)});
  checkedRequest(p,r.id);if(last==='action'){const action=String(b.action);if(action==='cancel'&&r.owner_id===s.user.id)r.status='cancelled';else if(action==='decline'){const share=r.shares.find(x=>x.payer_id===s.user.id&&x.status==='open');if(!share)error('No unpaid share belongs to you.',403);share.status='declined'}else if(action==='remind'&&r.owner_id===s.user.id)notice(s,'requests-received','Synthetic reminder recorded',r.id);else error('Action not permitted.',403);return yes({status:'accepted'})}
  const share=r.shares.find(x=>x.payer_id===s.user.id&&x.status==='open'),amount=minor(b.amount_minor);if(!share||amount<=0n||amount>minor(share.amount_minor)-minor(share.received_minor))error('Choose an amount within your unpaid share.');const q:Quote={id:id('quo'),kind:'internal',amount_minor:amount.toString(),fee_minor:'0',total_minor:amount.toString(),currency:'NGN',destination:{user_id:r.owner_id,account_name:r.requester_name},narration:r.memo,policy_version:1,expires_at:new Date(Date.now()+300000).toISOString(),used:false};s.quotes[q.id]=q;p.links[q.id]={request:r.id,share:share.id,amount:q.amount_minor};return yes(q);
 }
 if(path==='/v1/insights/categories')return yes(categories);
 if(path==='/v1/budgets'){const month=text(b.month,7),category=text(b.category,30),amount=minor(b.amount_minor);if(!categories.includes(category)||!/^\d{4}-\d{2}$/.test(month)||amount<=0n)error('Invalid budget.',400);(p.budgets[month]??={})[category]=amount.toString();return yes({status:'accepted'})}
 if(path.startsWith('/v1/budgets/')&&method==='DELETE'){delete p.budgets[url.searchParams.get('month')||'']?.[last];return yes()}
 if(path==='/v1/insights'){
  const month=url.searchParams.get('month')||localMonth(),totals:Record<string,bigint>={};let spent=0n,excluded=0n,fees=0n;for(const pay of s.payments.filter(x=>localMonth(new Date(x.updated_at))===month&&x.direction==='outgoing'&&x.status==='succeeded')){const a=p.annotations[pay.id];fees+=minor(pay.fee_minor);if(a?.excluded){excluded+=minor(pay.total_minor);continue}const category=a?.category||(pay.kind==='bill'?'other':'transfers');totals[category]=(totals[category]||0n)+minor(pay.total_minor);spent+=minor(pay.total_minor)}const entries=s.entries.filter(x=>localMonth(new Date(x.created_at))===month);const inTotal=entries.reduce((n,x)=>n+(BigInt(x.delta_minor)>0n?BigInt(x.delta_minor):0n),0n),outTotal=entries.reduce((n,x)=>n+(BigInt(x.delta_minor)<0n?-BigInt(x.delta_minor):0n),0n);return yes({month,currency:'NGN',timezone:'Africa/Lagos',money_in_minor:inTotal.toString(),money_out_minor:outTotal.toString(),spending_minor:spent.toString(),excluded_minor:excluded.toString(),fees_minor:fees.toString(),previous_money_out_minor:'0',next_30_days_reminders_minor:p.reminders.filter(x=>x.status==='active').reduce((n,x)=>n+minor(x.amount_minor),0n).toString(),categories:[...new Set([...Object.keys(totals),...Object.keys(p.budgets[month]||{})])].map(category=>({category,spent_minor:(totals[category]||0n).toString(),budget_minor:p.budgets[month]?.[category]||'0'})),estimate_note:'Synthetic planning estimate; not an available-balance calculation.'});
 }
 if(path==='/v1/search'){const query=(url.searchParams.get('q')||'').toLowerCase();return yes({payments:s.payments.filter(x=>x.id.toLowerCase().includes(query)||(s.quotes[x.quote_id]?.narration||'').toLowerCase().includes(query)).slice(0,50),limit:50})}
 if(path==='/v1/funding/account'){if(method==='POST')p.funding={id:id('fundacct'),state:'active',configured:true,updated_at:now(),details:{reference:'synthetic-provisioning',state:'active',account_name:s.user.name,account_number:'TEST-NOT-A-BANK-ACCOUNT',institution:'Synthetic demonstration only',synthetic:true}};return yes(p.funding)}
 if(path==='/v1/identity/draft'){if(method==='PATCH'){if(Number(b.version)!==p.draft.version)error('Draft changed; reload it.');if(p.draft.submitted_case)error('Submitted identity evidence is fixed.');p.draft={version:p.draft.version+1,draft:options.body as Identity};return yes(p.draft)}return yes(p.draft)}
 if(path==='/v1/identity/submit'){if(Number(b.version)!==p.draft.version||!p.draft.draft?.consent||!p.draft.draft.upload_ids.length)error('Save your details, choose evidence and provide consent.');const cid=id('kyc');p.draft.submitted_case=cid;s.kyc.unshift({id:cid,owner_id:s.user.id,status:'submitted',evidence_reference:'synthetic-private-evidence',created_at:now()});return yes({id:cid})}
 if(path==='/v1/uploads'){
  if(method==='GET')return yes(p.uploads.filter(x=>x.purpose===url.searchParams.get('purpose')&&x.case_id===(url.searchParams.get('case_id')||'')));
  const form=options.body;if(!(form instanceof FormData))error('Multipart upload required.',400);const file=form.get('file');if(!(file instanceof Blob))error('File required.',400);if(file.size>5*1024*1024)error('File exceeds five MiB.',400);const u:Upload={id:id('upload'),name:text((file as File).name||'synthetic-document.pdf'),purpose:String(form.get('purpose')),case_id:String(form.get('case_id')||''),mime:file.type,size:file.size,state:'local_unscanned',created_at:now()};p.uploads.unshift(u);return yes(u);
 }
 if(path.startsWith('/v1/uploads/')){const upload=p.uploads.find(x=>x.id===part[3]);if(!upload)error('Document not found.',404);if(method==='DELETE'){if(p.draft.submitted_case&&p.draft.draft?.upload_ids.includes(upload.id))error('Submitted evidence is retained.');p.uploads=p.uploads.filter(x=>x.id!==upload.id);return yes()}if(last==='download')return yes(new Blob(['SYNTHETIC REVIEW PLACEHOLDER. The review harness stores metadata only, not the original uploaded document.'],{type:'text/plain'}))}
 if(path==='/v1/me/email-change'){reauthenticate(b);const email=String(b.new_email||'');if(!email.endsWith('.invalid'))error('Use an example.invalid mailbox in synthetic review.',400);p.emailChange={id:id('change'),email};return yes({id:p.emailChange.id,expires_at:new Date(Date.now()+600000).toISOString()})}
 if(/^\/v1\/me\/email-change\/[^/]+\/verify$/.test(path)){if(!p.emailChange||p.emailChange.id!==part[4]||b.old_code!=='123456'||b.new_code!=='123456')error('Use 123456 for both synthetic mailbox codes.',401);s.user.email=p.emailChange.email;delete p.emailChange;s.signedIn=false;return yes({status:'accepted'})}
 if(path==='/v1/me/closure'){const blockers:string[]=[];if(BigInt(s.balance)!==0n||BigInt(s.held)!==0n)blockers.push('Settle and withdraw the account balance and held funds.');if(s.payments.some(x=>['pending','accepted','submitted','pending_review'].includes(x.status)))blockers.push('Resolve pending payments.');if(s.cases.some(x=>x.status!=='resolved'))blockers.push('Resolve open support cases.');if(method==='POST'){reauthenticate(b);if(blockers.length)error(blockers.join(' '));s.user.status='closed';s.signedIn=false;p.reminders.forEach(x=>x.status='cancelled');p.mandates.forEach(x=>x.status='cancelled');return yes({status:'accepted'})}return yes({can_close:blockers.length===0,balance:{currency:'NGN',balance_minor:s.balance,held_minor:s.held,available_minor:(BigInt(s.balance)-BigInt(s.held)).toString()},pending_payments:s.payments.filter(x=>['pending','accepted','submitted','pending_review'].includes(x.status)).length,open_cases:s.cases.filter(x=>x.status!=='resolved').length,retention:'Account closure does not erase required financial records.'})}
 if(path==='/v1/me/export'){reauthenticate(b);return yes({profile:s.user,preferences:s.preferences,controls:p.controls,scope:'Profile and preferences only; financial statements are available separately.',generated_at:now()})}
 if(/^\/v1\/support\/cases\/[^/]+\/(timeline|escalate)$/.test(path)){const cid=part[4],c=s.cases.find(x=>x.id===cid);if(!c)error('Case not found.',404);if(last==='timeline')return yes((p.events[cid]||[{action:'case.created',created_at:c.created_at}]).map(x=>({event:x.action,at:x.created_at})));if(c.status==='resolved')error('Resolved case cannot be escalated.');c.status='escalated';p.events[cid]=[...(p.events[cid]||[]),{action:'case.escalated',created_at:now()}];return yes({status:'accepted'})}
 return {handled:false};
}
