import {PasskeySignIn} from './security_parity';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, Eye, EyeOff, LockKeyhole, ShieldCheck } from 'lucide-react';
import { Link, Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom';
import { useAction, useApp } from '../state';
import { Brand, EnvironmentBar, RouteFocus, ThemeToggle } from '../components/layout';
import { Button, Callout, ErrorBox, Field, Form, SecurityNote } from '../components/ui';
import { isReview } from '../api/config';

function Password({ label = 'Password', value, onChange, newPassword = false }: { label?: string; value: string; onChange(v: string): void; newPassword?: boolean }) {
  const [visible, setVisible] = useState(false);
  return <Field label={label} hint={newPassword ? 'Use at least 12 characters. Spaces and passphrases are welcome.' : undefined}><span className="password-field"><input required type={visible ? 'text' : 'password'} value={value} onChange={e => onChange(e.target.value)} minLength={newPassword ? 12 : 1} maxLength={256} autoComplete={newPassword ? 'new-password' : 'current-password'}/><button type="button" onClick={() => setVisible(v => !v)} aria-label={visible ? `Hide ${label.toLowerCase()}` : `Show ${label.toLowerCase()}`}>{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button></span></Field>;
}
export { Password };
export function AuthLayout() {
  return <><EnvironmentBar/><div className="auth-layout"><aside className="auth-story"><Brand inverse/><div className="auth-story-content"><span className="eyebrow light">YOUR EVERYDAY, SIMPLIFIED</span><h2>Less friction.<br/>More living.</h2><p>Send money, settle your bills and keep track of it all — from one thoughtfully simple place.</p><div className="auth-illustration" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="mini-payment"><span className="round-icon"><ArrowUpRight size={25}/></span><div><strong>Every payment.<br/>One clear picture.</strong><span>Transfer · Pay · Keep track</span></div><span className="mini-check"><Check size={17}/></span></div></div><div className="auth-points"><span><ShieldCheck size={17}/>Private by design</span><span><Check size={17}/>Made for everyday use</span></div></div><small className="auth-footer">Qpay · Your money, in good order.</small></aside><div className="auth-main"><div className="auth-top"><span className="mobile-brand"><Brand/></span><ThemeToggle/></div><main className="auth-card"><RouteFocus/><Outlet/></main><p className="auth-help">Need help signing in? <Link to="/help">View sign-in help</Link></p></div></div></>;
}
export function LoginPage() {
  const { signIn, user, status, error: startupError, refresh, review } = useApp(); const a = useAction(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [mfa, setMfa] = useState(''); const [recovery, setRecovery] = useState(''); const [advanced, setAdvanced] = useState(false); const [useRecovery, setUseRecovery] = useState(false);
  const from = (location.state as { from?: string } | null)?.from;
  const destination = from?.startsWith('/') && !from.startsWith('//') && !from.includes('\\') && !from.startsWith('/login') ? from : '/';
  if (user && status === 'ready') return <Navigate to={destination} replace/>;
  return <><div className="auth-heading"><span className="eyebrow">WELCOME BACK</span><h1 tabIndex={-1}>Good to see you.</h1><p>Sign in to your Qpay account to continue.</p></div>{(location.state as { message?: string })?.message && <Callout title={(location.state as { message: string }).message}/>}{status === 'unavailable' && <ErrorBox error={startupError} retry={refresh}/>}
  {isReview && <div className="review-login"><strong>Synthetic review account</strong><p>No real money or personal data. The synthetic sign-in password remains Review-only-2026, including after a recovery rehearsal.</p><Button variant="quiet" onClick={() => { setEmail(review?.sampleEmail || 'review@qpay.example.invalid'); setPassword('Review-only-2026'); setMfa('123456'); }}>Fill sample sign-in <ArrowRight size={15}/></Button></div>}
  <Form onSubmit={() => void a.run(async () => { await signIn({ email: email.trim(), password, ...(mfa ? { mfa_code: mfa } : {}), ...(recovery ? { recovery_code: recovery } : {}) }); setPassword(''); setMfa(''); setRecovery(''); navigate(destination, { replace: true }); })}>
  <ErrorBox error={a.error}/><Field label="Email address"><input required type="email" autoComplete="username" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com" maxLength={254}/></Field><Password value={password} onChange={setPassword}/>
  <div className="form-between"><button className="text-link" type="button" aria-expanded={advanced} onClick={() => setAdvanced(v => !v)}>Use two-step verification</button><Link className="text-link" to="/forgot-password">Forgot password?</Link></div>
  {advanced && <>{useRecovery ? <Field label="Recovery code"><input value={recovery} onChange={e => setRecovery(e.target.value)} autoComplete="off" maxLength={100}/></Field> : <Field label="Authenticator code"><input inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" maxLength={6} value={mfa} onChange={e => setMfa(e.target.value)} placeholder="6-digit code"/></Field>}<button type="button" className="text-link" onClick={() => { setUseRecovery(v => !v); setMfa(''); setRecovery(''); }}>{useRecovery ? 'Use authenticator instead' : 'Use a recovery code instead'}</button></>}
  <Button type="submit" busy={a.busy} className="full">Sign in <ArrowRight size={18}/></Button></Form><PasskeySignIn/><p className="auth-switch">New to Qpay? <Link to="/register">Create an account</Link></p><SecurityNote/></>;
}
export function RegisterPage() {
  const { client } = useApp(); const navigate = useNavigate(); const a = useAction(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  return <><div className="auth-heading"><span className="eyebrow">A SIMPLER EVERYDAY</span><h1 tabIndex={-1}>Make room for more.</h1><p>Create your personal Qpay account.</p></div>{isReview && <Callout title="Use synthetic details only">Use an example.invalid email address. The review code and PIN are 123456.</Callout>}<Form onSubmit={() => void a.run(async () => { await client.request('POST', '/v1/auth/register', { body: { email: email.trim(), name: name.trim(), password } }); setPassword(''); navigate('/verify-email', { state: { email } }); })}><ErrorBox error={a.error}/><Field label="Full name"><input required autoComplete="name" value={name} onChange={e => setName(e.target.value)} maxLength={80}/></Field><Field label="Email address"><input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} maxLength={254}/></Field><Password label="Create password" value={password} onChange={setPassword} newPassword/><label className="checkbox"><input required type="checkbox"/><span>I am 18 or older and understand this is a test release, not a live financial service.</span></label><Button type="submit" busy={a.busy} className="full">Create account <ArrowRight size={18}/></Button></Form><p className="fineprint">Legal terms and the privacy notice require approval before live onboarding. <Link to="/help">Read the test-release information.</Link></p><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></>;
}
export function VerifyPage({ reset = false }: { reset?: boolean }) {
  const { client, toast, user, reloadUser } = useApp(); const a = useAction(); const resend = useAction(); const location = useLocation(); const navigate = useNavigate();
  const [email, setEmail] = useState((location.state as { email?: string })?.email || user?.email || ''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [sentAt, setSentAt] = useState(0);
  return <><span className="auth-icon"><LockKeyhole size={28}/></span><div className="auth-heading"><h1 tabIndex={-1}>{reset ? 'Choose a fresh start.' : 'Check your inbox.'}</h1><p>{reset ? 'Enter the recovery code and your new password.' : 'Enter the verification code sent to your email address.'}</p></div>{isReview && <Callout title="Synthetic challenge">Use code 123456. In API mode, retrieve local test codes through the backend’s controlled CLI.</Callout>}<Form onSubmit={() => void a.run(async () => { await client.request('POST', '/v1/auth/challenges/verify', { body: { email: email.trim(), purpose: reset ? 'reset' : 'verify', code, ...(reset ? { new_password: password } : {}) } }); setPassword(''); setCode(''); if (user && !reset) { await reloadUser(); navigate('/'); } else navigate('/login', { replace: true, state: { message: reset ? 'Password updated. Sign in with your new password.' : 'Email verified. You can now sign in.' } }); })}><ErrorBox error={a.error}/><Field label="Email address"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email"/></Field><Field label="Verification code"><input className="code-input" required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e => setCode(e.target.value)} placeholder="000000"/></Field>{reset && <Password label="New password" value={password} onChange={setPassword} newPassword/>}<Button type="submit" busy={a.busy} className="full">{reset ? 'Reset password' : 'Verify email'}<ArrowRight size={18}/></Button></Form><ErrorBox error={resend.error}/><div className="auth-switch">Didn’t receive a code? <Button variant="quiet" busy={resend.busy} onClick={() => void resend.run(async () => { if (Date.now() - sentAt < 60000) throw new Error('Wait one minute before requesting another code.'); if (!email) throw new Error('Enter your email address first.'); await client.request('POST', '/v1/auth/challenges', { body: { email, purpose: reset ? 'reset' : 'verify' } }); setSentAt(Date.now()); toast('A code was requested for an eligible account. Check your inbox.'); })}>Resend code</Button></div><Link to="/login" className="text-link">Back to sign in</Link></>;
}
export function ForgotPage() {
  const { client } = useApp(); const a = useAction(); const navigate = useNavigate(); const [email, setEmail] = useState('');
  return <><span className="auth-icon"><LockKeyhole size={28}/></span><div className="auth-heading"><h1 tabIndex={-1}>Let’s get you back in.</h1><p>We’ll send a recovery code if this email belongs to an eligible account.</p></div><Form onSubmit={() => void a.run(async () => { await client.request('POST', '/v1/auth/challenges', { body: { email: email.trim(), purpose: 'reset' } }); navigate('/reset-password', { state: { email } }); })}><ErrorBox error={a.error}/><Field label="Email address"><input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)}/></Field><Button type="submit" busy={a.busy} className="full">Request recovery code <ArrowRight size={18}/></Button></Form><p className="auth-switch"><Link to="/login">Back to sign in</Link></p></>;
}
export function AuthHelpPage() {
  return <><div className="auth-heading"><h1 tabIndex={-1}>A little help, right here.</h1><p>This web app is being prepared for in-person testing.</p></div><div className="help-sections"><h3>Unable to sign in?</h3><p>Check your email and password. Enabled two-step verification also needs an authenticator or recovery code.</p><h3>Testing with the backend</h3><p>Use the local API and synthetic accounts created through its administration command. Verification codes are never exposed through a public endpoint.</p><h3>Important account information</h3><p>There is no live-money approval in this release. Final legal terms, custody information, pricing and the privacy notice must be reviewed before launch.</p><Callout title="Never share your secrets">Support should never ask for your password, transaction PIN, authentication codes or recovery codes.</Callout><Link to="/login" className="button primary">Return to sign in <ArrowRight size={17}/></Link></div></>;
}
