import { useState } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Eye, EyeOff, Plus, ShieldCheck, Wallet as WalletIcon, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApp, useResource } from '../state';
import type { Funding, NoticeList, Payment, Wallet } from '../api/types';
import { dateTime, money } from '../api/money';
import { loadIntent } from '../api/recovery';
import { isReview } from '../api/config';
import { Badge, Button, Callout, Card, Empty, ErrorBox, Gap, Loading, PageTitle } from '../components/ui';
import { PaymentRows } from '../components/payments';

export function OverviewPage() {
  const { user } = useApp(); const balance = useResource<Wallet>('/v1/wallet'); const activity = useResource<Payment[]>('/v1/payments?limit=5'); const notices = useResource<NoticeList>('/v1/notifications?limit=5'); const [hidden, setHidden] = useState(false);
  const unresolved = loadIntent(user!.id);
  const complete = [user!.email_verified, user!.tier > 0, user!.pin_set, user!.mfa_enabled].filter(Boolean).length;
  return <><PageTitle eyebrow="YOUR EVERYDAY, AT A GLANCE" title={`Hello, ${user!.name.split(' ')[0]}.`} description="A little less admin. A little more peace of mind." action={<Link to="/transfers/new" className="button primary"><ArrowUpRight size={17}/>Send money</Link>}/>
  {unresolved?.phase === 'unknown' && <Callout tone="warning" title="A payment needs a status check"><p>We did not receive the final response. Check the original request before sending again.</p><Link className="text-link" to="/transfers/recovery">Recover the original request <ArrowRight size={15}/></Link></Callout>}
  {user!.status !== 'active' && <Callout tone="warning" title="Some account functions are restricted"><Link to="/support">Contact support</Link> to review the next steps. Your current records remain accessible.</Callout>}
  <div className="overview-top"><section className="balance-card"><div className="balance-head"><span><WalletIcon size={18}/>YOUR AVAILABLE BALANCE</span><Button variant="icon" onClick={() => setHidden(v => !v)} aria-label={hidden ? 'Show balances' : 'Hide balances'}>{hidden ? <EyeOff size={18}/> : <Eye size={18}/>}</Button></div>{balance.loading ? <Loading label="Reading wallet…"/> : balance.error ? <ErrorBox error={balance.error} retry={balance.reload}/> : <><p className="balance-value">{hidden ? '••••••' : money(balance.data!.available_minor)}</p><div className="balance-detail"><span>NGN wallet</span><span className="dot"/><span>{isReview ? 'Synthetic review balance' : 'From your account ledger'}</span></div><div className="balance-actions"><Link to="/wallet" className="button mint"><Plus size={17}/>Add money</Link><Link to="/transfers/new" className="button outline-light">Send money <ArrowUpRight size={17}/></Link></div><div className="balance-bottom"><span>On hold <strong>{hidden ? '••••' : money(balance.data!.held_minor)}</strong></span><span>Book balance <strong>{hidden ? '••••' : money(balance.data!.balance_minor)}</strong></span></div></>}</section>
  <Card className="readiness-card"><div className="readiness-heading"><span className="round-icon"><ShieldCheck size={24}/></span><span className="eyebrow">ACCOUNT CHECK-IN</span></div><h2>Ready for what’s next.</h2><p>A few simple steps help keep your account in good order.</p><div className="progress-line" role="img" aria-label={`${complete} of 4 account steps completed`}>{[0, 1, 2, 3].map(i => <span key={i} className={i < complete ? 'done' : ''}/>)}</div><div className="readiness-list"><span>Email verified <Badge status={user!.email_verified ? 'approved' : 'pending'}/></span><span>Identity review <Badge status={user!.tier > 0 ? 'approved' : 'pending'}/></span></div><Link to={user!.tier === 0 ? '/verification' : '/settings/security'} className="text-link">{user!.tier === 0 ? 'Complete verification' : 'Review account security'}<ArrowRight size={16}/></Link></Card></div>
  <div className="section-heading"><h2>What would you like to do?</h2><span>Everyday essentials</span></div><div className="quick-actions"><Link to="/transfers/new"><span className="quick-icon lavender"><ArrowUpRight size={23}/></span><strong>Send money</strong><small>To a bank or Qpay account</small><ArrowRight size={18}/></Link><Link to="/bills"><span className="quick-icon peach"><Zap size={23}/></span><strong>Pay a bill</strong><small>Airtime, data and more</small><ArrowRight size={18}/></Link><Link to="/wallet"><span className="quick-icon mint-bg"><ArrowDownLeft size={23}/></span><strong>Fund your wallet</strong><small>Manage incoming payments</small><ArrowRight size={18}/></Link></div>
  <div className="overview-bottom"><Card title="Recent activity" action={<Link to="/activity" className="text-link">View all <ArrowRight size={15}/></Link>}>{activity.loading ? <Loading/> : activity.error ? <ErrorBox error={activity.error} retry={activity.reload}/> : <PaymentRows payments={activity.data || []}/>}</Card><Card title="In the loop" action={<Link to="/notifications" className="icon-link" aria-label="View all notifications"><ArrowUpRight size={18}/></Link>}>{notices.loading ? <Loading/> : notices.error ? <ErrorBox error={notices.error}/> : notices.data?.items.length ? <div className="mini-notices">{notices.data.items.slice(0, 3).map(n => <Link key={n.id} to={`/notifications/view/${encodeURIComponent(n.reference)}`}><span className={`dot ${!n.read ? 'green' : ''}`}/><div><strong>{n.subject}</strong><small>{dateTime(n.created_at)}</small></div></Link>)}</div> : <Empty title="You’re all caught up"/>}<div className="help-tile"><strong>A question about a payment?</strong><p>Keep the original reference handy. We’ll help you find the next step.</p><Link to="/support" className="text-link">Visit support <ArrowRight size={15}/></Link></div></Card></div></>;
}
export function WalletPage() {
  const wallet = useResource<Wallet>('/v1/wallet'); const funding = useResource<Funding[]>('/v1/wallet/funding'); const [method, setMethod] = useState('bank');
  return <><PageTitle title="A home for your money." eyebrow="MY WALLET" description="See what’s available, what’s on hold and what’s arrived."/>{wallet.loading ? <Loading/> : wallet.error ? <ErrorBox error={wallet.error} retry={wallet.reload}/> : <div className="stat-grid">{[['Available to spend', wallet.data!.available_minor], ['Currently on hold', wallet.data!.held_minor], ['Book balance', wallet.data!.balance_minor]].map(([title, value]) => <Card key={title}><span className="eyebrow">{title}</span><h2 className="stat-value">{money(value)}</h2></Card>)}</div>}
  <div className="two-column"><Card title="Add money"><div className="tabs" aria-label="Funding method">{[['bank', 'Bank transfer'], ['card', 'Card'], ['ussd', 'USSD']].map(([id, label]) => <button key={id} onClick={() => setMethod(id)} className={method === id ? 'active' : ''}>{label}</button>)}</div><div className="funding-visual"><span className="round-icon"><WalletIcon size={30}/></span><h3>{method === 'bank' ? 'Your account details, right here.' : method === 'card' ? 'A secure hosted checkout.' : 'A bank-approved USSD journey.'}</h3><p>{method === 'bank' ? 'Once a funding account is issued, this panel will show the verified bank name, account holder, account number and copy controls.' : method === 'card' ? 'Card entry belongs in the selected provider’s secure checkout. We do not collect card numbers or security codes in this app.' : 'Your chosen bank and provider must issue the payment instruction. This app will not invent a USSD code.'}</p></div><Gap id={method === 'bank' ? 'GAP-01' : 'GAP-02'} title="Funding integration to be reviewed">The current API can list posted funding, but does not yet provision a funding account or initiate this funding method. No deposit details are fabricated.</Gap></Card><Card title="Incoming payments">{funding.loading ? <Loading/> : funding.error ? <ErrorBox error={funding.error} retry={funding.reload}/> : funding.data?.length ? <div className="data-list">{funding.data.map(f => <div key={f.id}><span className="transaction-icon incoming"><ArrowDownLeft size={18}/></span><div><strong>Wallet credit</strong><small>{dateTime(f.created_at)}</small><code>{f.id}</code></div><strong className="credit">+{money(f.amount_minor)}</strong></div>)}</div> : <Empty title="No incoming payments yet">Confirmed wallet credits will appear here.</Empty>}<Callout title="Available and held are different">Held funds remain part of your book balance but are not available for another payment. A delayed notification does not change the balance.</Callout></Card></div></>;
}
