import {ExactRecipient} from '../components/parity';
import {BillerAvailability} from '../components/payment_parity';
import type {SavedBill} from '../api/parity';
import { operationID } from '../api/id';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, CheckCircle2, Clock3, Landmark, Plus, Search, Send, ShieldCheck, Smartphone, Tv, UsersRound, Wifi, Zap } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { useAction, useApp, useResource } from '../state';
import type { Approval, Bank, Beneficiary, Enquiry, Kind, Payment, Product, Quote, QuoteInput } from '../api/types';
import { APIError } from '../api/client';
import { amountInput, money, parseAmount } from '../api/money';
import { loadIntent, saveIntent, clearIntent } from '../api/recovery';
import { isReview } from '../api/config';
import { Badge, Button, Callout, Card, Empty, ErrorBox, Field, Form, Loading, PageTitle, SecurityNote, Steps } from '../components/ui';
import { PaymentRows } from '../components/payments';

export function TransferLanding() {
  const recent = useResource<Payment[]>('/v1/payments?limit=20');
  return <><PageTitle title="Send it with confidence." eyebrow="TRANSFERS" description="Choose a destination. Review the exact cost. Then authorise your payment."/><div className="transfer-options"><Link className="transfer-option" to="/transfers/new?type=bank"><span className="quick-icon mint-bg"><Landmark size={28}/></span><div><span className="eyebrow">BANK TRANSFER</span><h2>To a bank account.</h2><p>Verify the account holder before you send.</p></div><ArrowUpRight size={24}/></Link><Link className="transfer-option" to="/transfers/new?type=internal"><span className="quick-icon lavender"><UsersRound size={28}/></span><div><span className="eyebrow">QPAY TRANSFER</span><h2>To another Qpay user.</h2><p>Find their opt-in handle or use an exact account ID.</p></div><ArrowUpRight size={24}/></Link></div><Card title="Recent transfers" action={<Link to="/activity" className="text-link">View activity <ArrowRight size={16}/></Link>}>{recent.loading ? <Loading/> : recent.error ? <ErrorBox error={recent.error} retry={recent.reload}/> : <PaymentRows payments={(recent.data || []).filter(p => p.kind !== 'bill').slice(0, 6)}/>}</Card></>;
}
export function NewBeneficiary({ onSaved,onOneOff }: { onSaved(id: string): void;onOneOff?:(enquiry:Enquiry)=>void }) {
  const { client, invalidate } = useApp(); const banks = useResource<Bank[]>('/v1/banks'); const action = useAction();
  const [bank, setBank] = useState(''); const [account, setAccount] = useState(''); const [label, setLabel] = useState(''); const [enquiry, setEnquiry] = useState<Enquiry>();
  const reset = () => { setEnquiry(undefined); action.clear(); };
  return <div className="new-beneficiary"><ErrorBox error={banks.error} retry={banks.reload}/><ErrorBox error={action.error}/><Field label="Bank"><select required value={bank} onChange={e => { setBank(e.target.value); reset(); }} disabled={banks.loading || action.busy}><option value="">{banks.loading ? 'Loading banks…' : 'Choose a bank'}</option>{banks.data?.map(b => <option value={b.code} key={b.code}>{b.name}</option>)}</select></Field><Field label="Account number"><input value={account} required inputMode="numeric" pattern="[0-9]{10}" maxLength={10} autoComplete="off" placeholder="10-digit account number" onChange={e => { setAccount(e.target.value.replace(/\D/g, '')); reset(); }} disabled={action.busy}/></Field>
  {!enquiry ? <Button variant="secondary" busy={action.busy} disabled={!bank || account.length !== 10} onClick={() => void action.run(async () => { const e = await client.request<Enquiry>('POST', '/v1/banks/enquiries', { body: { bank_code: bank, account_number: account } }); if (!e.id || !e.name || Date.parse(e.expires_at) <= Date.now()) throw new Error('The account enquiry did not return a current verified name.'); setEnquiry(e); setLabel(e.name.slice(0, 80)); })}>Check account name <Search size={16}/></Button> : <><div className="verified-name"><CheckCircle2 size={20}/><div><small>ACCOUNT NAME RETURNED BY THE API</small><strong>{enquiry.name}</strong></div></div>{onOneOff&&<Button variant="primary" onClick={()=>{if(Date.parse(enquiry.expires_at)<=Date.now()){setEnquiry(undefined);return};onOneOff(enquiry)}}>Use once without saving</Button>}<Field label="Saved recipient label"><input maxLength={80} required value={label} onChange={e => setLabel(e.target.value)} disabled={action.busy}/></Field><p className="fineprint">Saving is optional for a one-off transfer. A saved recipient is checked again before every new quote.</p><Button variant="secondary" busy={action.busy} disabled={!label.trim()} onClick={() => void action.run(async () => { if (Date.parse(enquiry.expires_at) <= Date.now()) { setEnquiry(undefined); throw new Error('The enquiry expired. Check the account name again.'); } const result = await client.request<{ id: string }>('POST', '/v1/beneficiaries', { body: { enquiry_id: enquiry.id, label: label.trim() } }); onSaved(result.id); invalidate(); })}>Save and use recipient <ArrowRight size={16}/></Button></>}
  </div>;
}
export function PaymentPage({ bill = false }: { bill?: boolean }) {
  const { client, user, capabilities, toast, invalidate } = useApp(); const [params] = useSearchParams(); const navigate = useNavigate();
  const [kind, setKind] = useState<Kind>(bill ? 'bill' : params.get('type') === 'internal' ? 'internal' : 'bank');
  const beneficiaries = useResource<Beneficiary[]>(kind === 'bank' ? '/v1/beneficiaries' : null); const products = useResource<Product[]>(bill ? '/v1/bills/products' : null);
  const [oneOff,setOneOff]=useState<Enquiry>();
  const [newRecipient, setNewRecipient] = useState(false); const [beneficiary, setBeneficiary] = useState(params.get('beneficiary') || ''); const [recipient, setRecipient] = useState(''); const [product, setProduct] = useState(params.get('product') || ''); const [customer, setCustomer] = useState('');
  const [amount, setAmount] = useState(''); const [narration, setNarration] = useState(''); const [step, setStep] = useState(0); const [quote, setQuote] = useState<Quote>(); const [pin, setPin] = useState(''); const [mfa, setMfa] = useState(''); const [time, setTime] = useState(Date.now()); const action = useAction();
  const selectedProduct = products.data?.find(p => p.id === product);
  const unresolved = loadIntent(user!.id);
  const savedBills = useResource<SavedBill[]>(bill && params.get('saved') ? '/v1/saved-bills' : null);
  useEffect(()=>{const v=savedBills.data?.find(v=>v.id===params.get('saved'));if(v){setProduct(v.product_id);setCustomer(v.customer_id);setAmount(amountInput(v.amount_minor));setNarration(v.label)}},[savedBills.data]);
  useEffect(()=>{const id=params.get('quote');if(!id)return;let active=true;void client.request<Quote>('GET','/v1/quotes/'+encodeURIComponent(id)).then(q=>{if(active){setKind(q.kind);setQuote(q);setAmount(amountInput(q.amount_minor));setNarration(q.narration);setStep(1);setTime(Date.now())}}).catch(e=>{if(active)action.setError(e)});return()=>{active=false}},[params.get('quote')]);
  useEffect(()=>{const id=params.get('repeat');if(!id)return;let active=true;void client.request<{kind:Kind;amount_minor:string;narration:string;destination:Quote['destination']}>('GET',`/v1/payments/${encodeURIComponent(id)}/draft`).then(async d=>{if(!active)return;setKind(d.kind);setAmount(amountInput(d.amount_minor));setNarration(d.narration);if(d.kind==='internal')setRecipient(d.destination.user_id||'');if(d.kind==='bill'){setProduct(d.destination.product_id||'');setCustomer(d.destination.customer_id||'')}if(d.kind==='bank'){const result=await client.request<Enquiry>('POST','/v1/banks/enquiries',{body:{bank_code:d.destination.bank_code,account_number:d.destination.account_number}});if(active)setOneOff(result)}}).catch(e=>{if(active)action.setError(e)});return()=>{active=false}},[params.get('repeat')]);

  useEffect(() => { if (!selectedProduct) return; if (!selectedProduct.variable_amount) setAmount(amountInput(selectedProduct.amount_minor)); }, [selectedProduct?.id]);
  useEffect(() => { if (!quote) return; const t = setInterval(() => setTime(Date.now()), 1000); return () => clearInterval(t); }, [quote]);
  const expired = quote ? time >= Date.parse(quote.expires_at) : false;
  const canExecute = Boolean(capabilities && (isReview || ['local', 'staging'].includes(capabilities.environment)) && user?.status === 'active');
  const edit = () => { setStep(0); setQuote(undefined); setPin(''); setMfa(''); action.clear(); };
  async function getQuote() {
    if (!canExecute) throw new Error('Payment submission is restricted to the approved test environment.');
    if (!navigator.onLine) throw new Error('Reconnect before requesting a quote.');
    const amount_minor = parseAmount(amount);
    const body: QuoteInput = { kind, amount_minor, currency: 'NGN', narration: narration.trim() };
    if (!body.narration || body.narration.length > 100) throw new Error('Add a payment note of no more than 100 characters.');
    if (kind === 'internal') body.recipient_id = recipient.trim();
    if (kind === 'bank') { if(oneOff){body.enquiry_id=oneOff.id}else{if (!beneficiary) throw new Error('Select or verify a recipient first.'); body.beneficiary_id = beneficiary;} }
    if (kind === 'bill') {
      if (!selectedProduct || !customer.trim()) throw new Error('Choose a current product and enter the customer identifier.');
      const validation = await client.request<Enquiry>('POST', '/v1/bills/validations', { body: { product_id: product, customer_id: customer.trim(), amount_minor } });
      if (!validation.id || !validation.name || validation.amount_minor !== amount_minor || Date.parse(validation.expires_at) <= Date.now()) throw new Error('Bill validation returned an incomplete or expired result.');
      body.validation_id = validation.id;
    }
    const q = await client.request<Quote>('POST', '/v1/quotes', { body });
    if (q.kind !== kind || q.amount_minor !== amount_minor || kind === 'internal' && q.destination.user_id !== body.recipient_id) throw new Error('The returned quote does not match the requested payment.');
    setQuote(q); setStep(1); setTime(Date.now());
  }
  async function confirm() {
    if (!quote || expired || !canExecute || !navigator.onLine) throw new Error('The quote expired or payment submission is unavailable. Review the details again.');
    if (loadIntent(user!.id)) throw new Error('Check your existing saved payment request before submitting another.');
    const approval = await client.request<Approval>('POST', `/v1/quotes/${encodeURIComponent(quote.id)}/authorisations`, { body: { pin, ...(mfa ? { mfa_code: mfa } : {}) } });
    if (approval.quote_id !== quote.id || !approval.authorisation_token || Date.parse(approval.expires_at) <= Date.now()) throw new Error('The authorisation is invalid or expired.');
    const intent = { version: 1 as const, owner: user!.id, quoteId: quote.id, idempotencyKey: operationID(), createdAt: new Date().toISOString(), phase: 'submitting' as const };
    saveIntent(intent);
    try {
      const payment = await client.request<Payment>('POST', '/v1/payments', { body: { quote_id: quote.id, authorisation_token: approval.authorisation_token }, idempotencyKey: intent.idempotencyKey });
      if (payment.quote_id !== quote.id || payment.amount_minor !== quote.amount_minor) throw new APIError(502, 'invalid_response', 'The payment response does not match the original quote.');
      saveIntent({ ...intent, paymentId: payment.id, phase: 'accepted' }); invalidate(); navigate(`/activity/${encodeURIComponent(payment.id)}`, { replace: true });
    } catch (e) {
      if (e instanceof APIError && e.status >= 400 && e.status < 500 && e.code !== 'invalid_response' && e.status !== 408) { clearIntent(); throw e; }
      saveIntent({ ...intent, phase: 'unknown' }); toast('The response was not confirmed. Check the original request, not a replacement.'); navigate('/transfers/recovery', { replace: true });
    } finally { setPin(''); setMfa(''); }
  }
  return <><Link to={bill ? '/bills' : '/transfers'} className="back-link"><ArrowLeft size={16}/>{bill ? 'All bill categories' : 'Transfers'}</Link><PageTitle title={bill ? 'One less thing on your list.' : 'Where should we send it?'} eyebrow={bill ? 'PAY A BILL' : 'SEND MONEY'} description="Nothing moves until you review and authorise the exact quote."/><div className="payment-grid"><Card className="payment-form"><Steps current={step} labels={['Details', 'Review', 'Authorise']}/>
  {!canExecute && <Callout tone="warning" title="Payment submission is unavailable">This test release blocks production money movement and restricted accounts. You can still review the interface and account records.</Callout>}
  {unresolved && <Callout tone="warning" title="Check your existing payment first"><Link to={unresolved.paymentId ? `/activity/${unresolved.paymentId}` : '/transfers/recovery'}>Open the saved original request</Link> before creating another payment.</Callout>}
  {step === 0 && <Form onSubmit={() => void action.run(getQuote)}><ErrorBox error={action.error}/><fieldset disabled={action.busy || Boolean(unresolved)}>
    {!bill && <div className="tabs"><button type="button" className={kind === 'bank' ? 'active' : ''} onClick={() => { setKind('bank'); action.clear(); }}><Landmark size={16}/>Bank account</button><button type="button" className={kind === 'internal' ? 'active' : ''} onClick={() => { setKind('internal'); action.clear(); }}><UsersRound size={16}/>Qpay account</button></div>}
    {kind === 'bank' && <><div className="form-between"><h3>Recipient</h3><button type="button" className="text-link" onClick={() => setNewRecipient(v => !v)}>{newRecipient ? 'Use a saved recipient' : '+ New recipient'}</button></div>{newRecipient ? <NewBeneficiary onOneOff={v=>{setOneOff(v);setBeneficiary('');setNewRecipient(false)}} onSaved={v => { setBeneficiary(v);setOneOff(undefined); setNewRecipient(false); }}/> : <><ErrorBox error={beneficiaries.error} retry={beneficiaries.reload}/><Field label="Saved beneficiary"><select value={beneficiary} onChange={e => {setBeneficiary(e.target.value);setOneOff(undefined)}} required={!oneOff}><option value="">Choose a recipient</option>{beneficiaries.data?.map(b => <option key={b.id} value={b.id}>{b.label} · {b.account_name}</option>)}</select></Field>{oneOff&&<Callout tone="success" title="One-off verified recipient">{oneOff.name} · not added to saved beneficiaries</Callout>}{!beneficiaries.loading && !beneficiaries.data?.length && <p className="fineprint">No saved recipients. Add a new recipient to verify their account.</p>}</>}</>}
    {kind === 'internal' && <><ExactRecipient onSelected={id=>setRecipient(id)}/><Field label="Recipient Qpay account ID" hint="Exact account ID from your recipient, or use the handle lookup above."><input required value={recipient} onChange={e => setRecipient(e.target.value)} placeholder={isReview ? 'usr_review_tunde_02' : 'usr_…'} minLength={8} maxLength={100} autoComplete="off"/></Field></>}
    {bill && <><ErrorBox error={products.error} retry={products.reload}/><Field label="Bill product"><select required value={product} onChange={e => setProduct(e.target.value)}><option value="">Choose a product</option>{products.data?.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Customer / service identifier" hint="Enter the phone, meter, smartcard or account identifier required by the selected biller."><input required value={customer} onChange={e => setCustomer(e.target.value)} maxLength={100} autoComplete="off"/></Field></>}
    {bill&&product&&<BillerAvailability product={product}/>}<div className="field-divider"/><Field label="Amount (NGN)" hint="Enter naira and kobo, for example 1000.00. Fees appear in the API quote."><span className="amount-input"><span>₦</span><input required inputMode="decimal" value={amount} readOnly={bill && Boolean(selectedProduct && !selectedProduct.variable_amount)} onChange={e => setAmount(e.target.value)} placeholder="0.00" maxLength={20}/></span></Field><Field label="Payment note"><input required value={narration} onChange={e => setNarration(e.target.value)} maxLength={100} placeholder={bill ? 'For this month’s bill' : 'What is this payment for?'}/></Field><Button type="submit" busy={action.busy} disabled={!canExecute || Boolean(unresolved) || kind === 'bank' && !beneficiary && !oneOff} className="full">{bill ? 'Validate bill & review' : 'Review transfer'}<ArrowRight size={17}/></Button></fieldset></Form>}
    {step > 0 && quote && <><div className="quote-heading"><span className="round-icon"><Send size={24}/></span><h2>{money(quote.amount_minor)}</h2><p>to {quote.destination.account_name || quote.destination.user_id || 'the validated bill account'}</p></div><dl className="detail-list"><div><dt>{kind === 'internal' ? 'Qpay account' : kind === 'bank' ? 'Bank account' : 'Service account'}</dt><dd><code>{quote.destination.account_number || quote.destination.user_id || quote.destination.customer_id}</code></dd></div><div><dt>Payment note</dt><dd>{quote.narration}</dd></div><div><dt>Amount</dt><dd>{money(quote.amount_minor)}</dd></div><div><dt>Fee</dt><dd>{money(quote.fee_minor)}</dd></div><div className="total"><dt>Total debit</dt><dd>{money(quote.total_minor)}</dd></div></dl><div className={`quote-expiry ${expired ? 'expired' : ''}`}><Clock3 size={16}/>{expired ? 'This quote has expired.' : `Quote expires in ${Math.max(0, Math.ceil((Date.parse(quote.expires_at) - time) / 1000))} seconds.`}</div><ErrorBox error={action.error}/>
    {step === 1 ? <><p className="fineprint">Check the account and amount carefully. This quote is bound to the displayed details and policy version {quote.policy_version}.</p><Button className="full" disabled={expired || !canExecute} onClick={() => setStep(2)}>Continue to authorisation <ArrowRight size={17}/></Button></> : <Form onSubmit={() => void action.run(confirm)}>{isReview && <Callout title="Review PIN: 123456">This authorises a synthetic fixture only.</Callout>}<Field label="Transaction PIN"><input required type="password" pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="off" value={pin} onChange={e => setPin(e.target.value)} placeholder="6-digit PIN" disabled={action.busy}/></Field>{user?.mfa_enabled && <Field label="Authenticator code"><input required pattern="[0-9]{6}" maxLength={6} inputMode="numeric" autoComplete="one-time-code" value={mfa} onChange={e => setMfa(e.target.value)} disabled={action.busy}/></Field>}<Button type="submit" className="full" disabled={expired || !canExecute || Boolean(unresolved)} busy={action.busy}><ShieldCheck size={18}/>{isReview ? 'Submit synthetic payment' : 'Authorise payment'}</Button></Form>}<Button variant="quiet" disabled={action.busy} onClick={edit}><ArrowLeft size={16}/>{expired ? 'Request a new quote' : 'Edit payment details'}</Button></>}
  </Card><div className="payment-aside"><span className="round-icon"><ShieldCheck size={28}/></span><h2>A moment to check.<br/>A better way to pay.</h2><p>We’ll show the verified details and exact fees before asking for your approval.</p><ol className="assurance-list"><li><span>01</span><div><strong>Know the destination</strong><p>Review the account name returned by the API.</p></div></li><li><span>02</span><div><strong>Know the full cost</strong><p>Quotes include the amount, fee and total debit.</p></div></li><li><span>03</span><div><strong>Keep one clear reference</strong><p>A delayed response is tracked, not submitted twice.</p></div></li></ol><SecurityNote/>{!user?.pin_set && <Callout title="Set your transaction PIN first"><Link to="/settings/security">Open security settings</Link> to create a PIN before authorising a payment.</Callout>}</div></div></>;
}
const categories = [
  { id: 'airtime', name: 'Airtime', sub: 'Keep the conversations going.', icon: Smartphone, tone: 'lavender' },
  { id: 'data', name: 'Mobile data', sub: 'Stay a little more connected.', icon: Wifi, tone: 'blue-bg' },
  { id: 'electricity', name: 'Electricity', sub: 'Keep your everyday powered.', icon: Zap, tone: 'peach' },
  { id: 'television', name: 'Television', sub: 'Your favourites, uninterrupted.', icon: Tv, tone: 'pink-bg' },
  { id: 'internet', name: 'Internet', sub: 'For work, play and everything.', icon: Wifi, tone: 'mint-bg' },
  { id: 'other', name: 'Other bills', sub: 'Find supported services here.', icon: Landmark, tone: 'cream-bg' },
];
export function categoryOf(p: Product): string {
  const value = `${p.category} ${p.name}`.toLowerCase();
  if (/airtime/.test(value)) return 'airtime'; if (/data/.test(value)) return 'data'; if (/electric|power|energy/.test(value)) return 'electricity'; if (/television|tv|cable/.test(value)) return 'television'; if (/internet|broadband/.test(value)) return 'internet'; return 'other';
}
export function BillsPage() {
  const products = useResource<Product[]>('/v1/bills/products'); const [category, setCategory] = useState('all'); const [search, setSearch] = useState('');
  const filtered = (products.data || []).filter(p => (category === 'all' || categoryOf(p) === category) && p.name.toLowerCase().includes(search.toLowerCase()));
  return <><PageTitle title="Bills handled. Day reclaimed." eyebrow="BILL PAYMENTS" description="Browse available products. Your biller’s current quote determines the final amount." action={<Link to="/bills/saved" className="button secondary">Saved household bills</Link>}/><div className="parity-toolbar"><Link to="/bills/tokens" className="button quiet">Token archive</Link><Link to="/calendar" className="button quiet">Bill calendar</Link></div><div className="bill-grid">{categories.map(({ id, name, sub, icon: Icon, tone }) => <button key={id} className={`bill-tile ${category === id ? 'selected' : ''}`} aria-pressed={category === id} onClick={() => setCategory(category === id ? 'all' : id)}><span className={`quick-icon ${tone}`}><Icon size={27}/></span><strong>{name}</strong><small>{sub}</small><span className="product-count">{(products.data || []).filter(p => categoryOf(p) === id).length} available products <ArrowRight size={14}/></span></button>)}</div><Card title={category === 'all' ? 'Available products' : categories.find(c => c.id === category)?.name} action={<button className="text-link" onClick={() => setCategory('all')}>Show all</button>}><div className="filters"><Field label="Find a product"><span className="search-input"><Search size={18}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search current bill products"/></span></Field></div>{products.loading ? <Loading label="Loading the bill catalogue…"/> : products.error ? <ErrorBox error={products.error} retry={products.reload}/> : filtered.length ? <div className="product-grid">{filtered.map(p => <Link key={p.id} to={`/bills/pay?product=${encodeURIComponent(p.id)}`} className="product-item"><span className="transaction-icon bill"><Zap size={19}/></span><div><strong>{p.name}</strong><small>{p.variable_amount ? 'Enter your amount' : money(p.amount_minor)} · Fees at quote</small></div><ArrowUpRight size={17}/></Link>)}</div> : <Empty title="No products available in this category">This screen shows only the products returned by the API. Try another category or refresh the catalogue.</Empty>}</Card></>;
}
