import { useState } from 'react';
import { ArrowRight, Bell, CheckCheck, Download, FileText } from 'lucide-react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { useAction, useApp, useResource } from '../state';
import type { NoticeList, Statement } from '../api/types';
import { dateTime, download, money, statementRange } from '../api/money';
import { Button, Callout, Card, Empty, ErrorBox, Field, Form, Loading, PageTitle } from '../components/ui';
function today() { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Lagos', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
export function StatementsPage() {
  const { client } = useApp(); const a = useAction(); const exportAction = useAction(); const day = today(); const [from, setFrom] = useState(day.slice(0, 7) + '-01'); const [to, setTo] = useState(day); const [statement, setStatement] = useState<Statement>(); const [range, setRange] = useState<{ from: string; to: string }>();
  return <><PageTitle title="Your records, ready when you are." eyebrow="STATEMENTS" description="Choose a date range in West Africa Time. The end date includes activity up to the current moment."/><Card><Form onSubmit={() => void a.run(async () => { const period = statementRange(from, to); const result = await client.request<Statement>('GET', '/v1/statements?' + new URLSearchParams(period)); if (!Array.isArray(result.entries) || result.currency !== 'NGN') throw new Error('The statement response is incomplete.'); setStatement(result); setRange(period); })} className="statement-form"><Field label="From date"><input required type="date" value={from} onChange={e => { setFrom(e.target.value); setStatement(undefined); }} max={day}/></Field><Field label="Through date"><input required type="date" value={to} onChange={e => { setTo(e.target.value); setStatement(undefined); }} min={from} max={day}/></Field><Button type="submit" busy={a.busy}><FileText size={17}/>Generate statement</Button></Form><ErrorBox error={a.error}/><p className="fineprint">Up to 366 days and 10,000 ledger entries per request. Oversized statements are rejected rather than silently truncated.</p></Card>{statement ? <Card title="Statement preview" action={<div className="row"><Button variant="secondary" busy={exportAction.busy} onClick={() => void exportAction.run(async () => { const blob = await client.request<Blob>('GET', '/v1/statements?' + new URLSearchParams({ ...range!, format: 'csv' }), { raw: true }); download('qpay-statement.csv', blob, 'text/csv'); })}><Download size={16}/>Download CSV</Button><Button variant="quiet" onClick={() => download('qpay-statement.json', JSON.stringify(statement, null, 2))}>JSON</Button></div>}><ErrorBox error={exportAction.error}/><div className="stat-grid two"><div><span className="eyebrow">OPENING BALANCE</span><h2 className="stat-value">{money(statement.opening_minor, true)}</h2></div><div><span className="eyebrow">CLOSING BALANCE</span><h2 className="stat-value">{money(statement.closing_minor, true)}</h2></div></div><p className="fineprint">{statement.entries.length} entries · Generated {dateTime(statement.generated_at)}</p>{statement.entries.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Reference</th><th>Type</th><th className="align-right">Amount</th></tr></thead><tbody>{statement.entries.map(e => <tr key={e.id}><td>{dateTime(e.created_at)}</td><td><code>{e.reference}</code></td><td>{e.kind.replaceAll('_', ' ')}</td><td className="align-right">{money(e.delta_minor, true)}</td></tr>)}</tbody></table></div> : <Empty title="No ledger entries in this period"/>}</Card> : <Empty title="A clear picture, in your own time">Your statement preview will appear here after the API returns it.</Empty>}<Callout title="Statements contain private financial information">Save downloaded files securely. The app does not cache statement contents for offline use.</Callout></>;
}
export function NotificationsPage() {
  const { client } = useApp(); const notices = useResource<NoticeList>('/v1/notifications?limit=100'); const a = useAction(); const [unread, setUnread] = useState(false);
  const items = (notices.data?.items || []).filter(n => !unread || !n.read);
  return <><PageTitle title="Good to be in the know." eyebrow="NOTIFICATIONS" description="Account updates in one place. Secret verification codes never appear in this feed." action={<Link to="/settings/preferences" className="button secondary">Manage preferences</Link>}/><Card title={`${notices.data?.unread ?? 0} unread updates`} action={<label className="checkbox inline"><input type="checkbox" checked={unread} onChange={e => setUnread(e.target.checked)}/>Unread only</label>}><ErrorBox error={a.error}/>{notices.loading ? <Loading/> : notices.error ? <ErrorBox error={notices.error} retry={notices.reload}/> : items.length ? <div className="notification-list">{items.map(n => <article key={n.id} className={n.read ? 'read' : 'unread'}><span className="transaction-icon"><Bell size={20}/></span><div><h3>{n.subject}</h3><p>{dateTime(n.created_at)}</p><Link to={`/notifications/view/${encodeURIComponent(n.reference)}`} className="text-link">View related record <ArrowRight size={14}/></Link></div>{!n.read && <Button variant="icon" aria-label={`Mark ${n.subject} read`} busy={a.busy} onClick={() => void a.run(async () => { await client.request('POST', `/v1/notifications/${encodeURIComponent(n.id)}/read`); notices.reload(); })}><CheckCheck size={20}/></Button>}</article>)}</div> : <Empty title="You’re all caught up"/>}<p className="fineprint">This feed displays up to 100 current API records. It is not proof that an email or push notification was delivered.</p></Card></>;
}
export function NotificationDestination() {
  const { reference = '' } = useParams();
  // Known internal prefixes only. References never grant permission by themselves.
  if (reference.startsWith('pay_')) return <Navigate to={`/activity/${encodeURIComponent(reference)}`} replace/>;
  if (reference.startsWith('case_')) return <Navigate to={`/support/${encodeURIComponent(reference)}`} replace/>;
  if (reference.startsWith('fund_')) return <Navigate to="/wallet" replace/>;
  if (reference.startsWith('kyc_')) return <Navigate to="/verification" replace/>;
  return <><PageTitle title="Your account update." eyebrow="NOTIFICATION"/><Card><p>For this update, review your profile, security settings or contact support. The reference is not a direct authorisation link.</p><code>{reference}</code><div className="row wrap"><Link to="/settings" className="button secondary">Account settings</Link><Link to="/support" className="button secondary">Support</Link></div></Card></>;
}
