import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { ArrowRight, CheckCheck, Download, FlaskConical, RotateCcw } from 'lucide-react';
import { apiBase, isReview, reviewTools } from '../api/config';
import { acceptanceJourneys, integrationGaps } from '../api/integration';
import { download } from '../api/money';
import type { Scenario } from '../review/transport';
import { useApp } from '../state';
import { Button, Callout, Card, Field, PageTitle } from '../components/ui';

type Verdict = 'not-tested' | 'passed' | 'failed' | 'blocked';
const key = 'qpf.uat-notes.v1';
interface Notes { session: string; results: Record<string, Verdict>; notes: string }
function initial(): Notes {
  try { const v = JSON.parse(sessionStorage.getItem(key) || 'null'); if (v && typeof v.session === 'string' && typeof v.notes === 'string' && v.results && typeof v.results === 'object') return v; } catch { /* Optional local notes are not an authentication store. */ }
  return { session: '', results: {}, notes: '' };
}
export function ReviewPage() {
  const { capabilities, review, invalidate, refresh, toast } = useApp();
  const [params] = useSearchParams(); const [selected, setSelected] = useState<Scenario>(review?.scenario || 'success'); const [notes, setNotes] = useState<Notes>(initial);
  const update = (v: Notes) => { setNotes(v); try { sessionStorage.setItem(key, JSON.stringify(v)); } catch { toast('Local storage is unavailable. Export your notes before leaving.'); } };
  if (!reviewTools) return <><PageTitle title="Integration status" description="This build does not enable the interactive review workspace."/><Callout title="Testing tools are not enabled">The customer application still keeps unsupported operations disabled. Ask your review facilitator for the dedicated test build.</Callout></>;
  const gaps = [...integrationGaps].sort((a, b) => a.id === params.get('gap') ? -1 : b.id === params.get('gap') ? 1 : 0);
  return <><PageTitle eyebrow="IN-PERSON ACCEPTANCE" title="Review workspace" description="Explore the experience. Record the gaps. Connect the next piece with evidence." action={<Button variant="secondary" onClick={() => download('qpay-review-notes.json', JSON.stringify({ schema_version: 1, exported_at: new Date().toISOString(), mode: isReview ? 'synthetic-ui-review' : 'api-connected', api_origin: apiBase || null, capabilities, ...notes, gaps: integrationGaps }, null, 2), 'application/json')}><Download size={17}/>Export review notes</Button>}/>
  <Callout title={isReview ? 'A complete UI rehearsal, not a banking simulation you can spend' : 'API-connected test workspace'} tone="warning">{isReview ? 'Every amount, recipient and transaction in this mode is synthetic. The review adapter does not call the backend, QPay or an email provider. Its scenarios are not evidence that the backend handles the same cases.' : 'This application calls the configured APIbackend directly. Only local or staging payment capabilities are allowed in this release. Actual QPay provider activation is a separate later decision.'}</Callout>
  <div className="two-column"><Card title="Connection and scope"><dl className="detail-list"><div><dt>Application mode</dt><dd>{isReview ? 'Synthetic UI review' : 'API connected'}</dd></div><div><dt>API origin</dt><dd className="mono wrap">{isReview ? 'No external calls' : apiBase}</dd></div><div><dt>Backend environment</dt><dd>{capabilities?.environment || 'Not established'}</dd></div><div><dt>Production execution</dt><dd>Blocked in this web release</dd></div><div><dt>Target upstream</dt><dd>APIbackend → QPay, after acceptance</dd></div></dl></Card>
  <Card title="Scenario controls" action={<FlaskConical size={20}/>}>{review ? <div className="form"><Field label="Next payment or request scenario"><select value={selected} onChange={e => { const value = e.target.value as Scenario; review.setScenario(value); setSelected(value); invalidate(); }}><option value="success">Confirmed success</option><option value="pending">Pending — no final result</option><option value="failed">Definitively unsuccessful</option><option value="unknown">Response lost after acceptance</option><option value="expired">Quote expires before approval</option><option value="insufficient">Insufficient funds</option><option value="restricted">Restricted account</option><option value="offline">API unavailable / offline</option></select></Field><div className="row wrap"><Button variant="secondary" onClick={() => { review.resolvePending(); invalidate(); toast('Synthetic pending operations resolved. No real payment was touched.'); }}><CheckCheck size={16}/>Resolve synthetic pending</Button><Button variant="quiet" onClick={() => { if (window.confirm('Reset synthetic account data and sign out? Review notes are kept.')) { review.reset(); setSelected('success'); refresh(); } }}><RotateCcw size={16}/>Reset sample data</Button></div><small>Review code and PIN: 123456. Use only synthetic identities.</small></div> : <p className="muted">Synthetic controls are excluded from API mode. Exercise backend failure cases through authorised local test fixtures, not browser-side overrides.</p>}</Card></div>
  <Card title="Acceptance checklist"><p className="muted">Manual observations only. No row starts as passed. Do not place credentials, account numbers, document data or other personal information in notes.</p><Field label="Review session label"><input maxLength={100} value={notes.session} onChange={e => update({ ...notes, session: e.target.value })} placeholder="For example: desktop review — session 01"/></Field><div className="uat-list">{acceptanceJourneys.map(([id, label, route]) => <div key={id} className="uat-item"><div><span className="eyebrow">{id}</span><p>{label}</p><Link to={route} className="text-link">Open journey <ArrowRight size={14}/></Link></div><label className="sr-only" htmlFor={id}>Result for {id}</label><select id={id} value={notes.results[id] || 'not-tested'} onChange={e => update({ ...notes, results: { ...notes.results, [id]: e.target.value as Verdict } })}><option value="not-tested">Not tested</option><option value="passed">Passed manually</option><option value="failed">Failed</option><option value="blocked">Blocked</option></select></div>)}</div><Field label="Review observations" hint="Stored in this browser tab only. Export before ending the session. Keep all observations free of sensitive data."><textarea rows={5} maxLength={12000} value={notes.notes} onChange={e => update({ ...notes, notes: e.target.value })} placeholder="Screen, expected behaviour, observed result, and suggested API adjustment…"/></Field></Card>
  <div className="section-heading"><div><span className="eyebrow">CONTRACT FOLLOW-THROUGH</span><h2>API connections and decisions</h2><p>UI-ready is not API-connected. These items remain explicitly open.</p></div><span className="badge pending">{gaps.length} tracked gaps</span></div><div className="gap-grid">{gaps.map(g => <Card key={g.id} className={params.get('gap') === g.id ? 'highlight-card' : ''}><div className="row between"><span className="eyebrow">{g.id}</span><span className="badge pending">{g.status}</span></div><h3>{g.title}</h3><p className="muted">{g.requirement}</p><div className="row between"><small>{g.api}</small><Link to={g.screen} className="text-link">Review screen <ArrowRight size={14}/></Link></div></Card>)}</div></>;
}
