import { useState } from 'react';
import { ArrowLeft, ArrowRight, LifeBuoy, MessageCircle, Plus, Send } from 'lucide-react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useAction, useApp, useResource } from '../state';
import type { Message, SupportCase } from '../api/types';
import { dateTime } from '../api/money';
import { Badge, Button, Callout, Card, Empty, ErrorBox, Field, Form, Gap, Loading, PageTitle } from '../components/ui';

export function SupportPage() {
  const cases = useResource<SupportCase[]>('/v1/support/cases');
  return <><PageTitle title="A little support goes a long way." eyebrow="HELP & SUPPORT" description="Keep conversations and payment references together, in one secure place." action={<Link to="/support/new" className="button primary"><Plus size={17}/>Start a conversation</Link>}/><div className="support-hero"><span className="round-icon"><LifeBuoy size={31}/></span><div><h2>Something doesn’t look right?</h2><p>For a delayed transfer or bill, check its original status first. You can then open a case linked to that payment.</p></div><Link className="button secondary" to="/activity">Find a transaction <ArrowRight size={16}/></Link></div><Card title="Your conversations">{cases.loading ? <Loading/> : cases.error ? <ErrorBox error={cases.error} retry={cases.reload}/> : cases.data?.length ? <div className="case-list">{cases.data.map(c => <Link key={c.id} to={`/support/${encodeURIComponent(c.id)}`}><span className="transaction-icon"><MessageCircle size={20}/></span><div><strong>{c.subject}</strong><small>{c.kind} · Updated {dateTime(c.updated_at)}</small><code>{c.id}</code></div><Badge status={c.status}/><ArrowRight size={17}/></Link>)}</div> : <Empty title="No support conversations yet">We’ll keep your case history here.</Empty>}</Card><div className="two-column"><Card title="Good to know"><h3>Why is my payment pending?</h3><p>The backend may be waiting for a confirmed provider outcome. A network timeout is not a definitive failure. Do not pay again just because a result is delayed.</p><h3>Where is my electricity token?</h3><p>Open the bill’s transaction details and check purchased value. Payment success and delivery can be separate.</p></Card><Card title="Keep your account private"><p>Do not send passwords, PINs, one-time codes, recovery codes or identity documents in a support message.</p><Gap id="GAP-07" title="Attachments and inbound email">The current API supports text conversations. Attachments, inbound email, assignment and SLA automation need additional backend work.</Gap></Card></div></>;
}
export function NewCasePage() {
  const { client } = useApp(); const navigate = useNavigate(); const [params] = useSearchParams(); const a = useAction();
  const [kind, setKind] = useState(params.get('kind') === 'dispute' ? 'dispute' : 'support'); const [payment, setPayment] = useState(params.get('payment') || ''); const [subject, setSubject] = useState(''); const [message, setMessage] = useState('');
  return <><Link to="/support" className="back-link"><ArrowLeft size={16}/>Support</Link><PageTitle title="Tell us what happened." eyebrow="NEW CONVERSATION" description="No passwords, PINs or identity documents, please."/><Card className="narrow"><Form onSubmit={() => void a.run(async () => { const c = await client.request<{ id: string }>('POST', '/v1/support/cases', { body: { kind, subject: subject.trim(), message: message.trim().replace(/\r?\n/g, ' '), ...(payment ? { payment_id: payment.trim() } : {}) } }); setMessage(''); navigate(`/support/${encodeURIComponent(c.id)}`, { replace: true }); })}><ErrorBox error={a.error}/><Field label="Conversation type"><select value={kind} onChange={e => setKind(e.target.value)}><option value="support">General support</option><option value="complaint">Complaint</option><option value="dispute">Payment dispute</option></select></Field><Field label={kind === 'dispute' ? 'Payment reference (required)' : 'Payment reference (optional)'} hint="Use a payment from your account activity."><input required={kind === 'dispute'} value={payment} onChange={e => setPayment(e.target.value)} maxLength={100}/></Field><Field label="Subject"><input required maxLength={140} value={subject} onChange={e => setSubject(e.target.value)} placeholder="How can we help?"/></Field><Field label="Message" hint="Up to 4,000 characters. Line breaks are converted to spaces for the current API."><textarea required maxLength={4000} value={message} onChange={e => setMessage(e.target.value)} rows={6} placeholder="Describe the issue and what you expected to happen."/></Field><Button type="submit" busy={a.busy}>Create support case <Send size={16}/></Button></Form></Card></>;
}
export function CasePage() {
  const { id = '' } = useParams(); const { user, client } = useApp(); const cases = useResource<SupportCase[]>('/v1/support/cases'); const messages = useResource<Message[]>(`/v1/support/cases/${encodeURIComponent(id)}/messages`); const a = useAction(); const [reply, setReply] = useState('');
  const current = cases.data?.find(c => c.id === id);
  return <><Link to="/support" className="back-link"><ArrowLeft size={16}/>All conversations</Link><PageTitle title={current?.subject || 'Your support conversation'} eyebrow="SECURE SUPPORT" description={id} action={current && <Badge status={current.status}/>}/><div className="two-column"><Card><ErrorBox error={messages.error} retry={messages.reload}/>{messages.loading ? <Loading/> : <div className="conversation">{messages.data?.map(m => <div className={`message ${m.author_id === user!.id ? 'own' : ''}`} key={m.id}><div className="message-meta"><strong>{m.author_id === user!.id ? 'You' : 'Support team'}</strong><small>{dateTime(m.created_at)}</small></div><p>{m.message}</p></div>)}</div>}<Form onSubmit={() => void a.run(async () => { await client.request('POST', `/v1/support/cases/${encodeURIComponent(id)}/messages`, { body: { message: reply.trim().replace(/\r?\n/g, ' ') } }); setReply(''); messages.reload(); cases.reload(); })}><ErrorBox error={a.error}/><Field label="Reply to this case" hint="Messages are private to authorised case participants. Do not include secrets."><textarea required maxLength={4000} value={reply} onChange={e => setReply(e.target.value)} rows={4}/></Field><Button type="submit" busy={a.busy} disabled={Boolean(messages.error)}>Send reply <Send size={16}/></Button></Form></Card><div className="stack">{current?.payment_id && <Card title="Linked transaction"><code>{current.payment_id}</code><Link className="button secondary full" to={`/activity/${encodeURIComponent(current.payment_id)}`}>Open transaction <ArrowRight size={16}/></Link></Card>}<Card title="What happens next"><p>Your message appears in the authorised support queue. A case does not automatically refund, cancel or repeat a payment.</p><Callout title="Keep the original reference">Support can investigate the original operation without asking you to submit it again.</Callout><Gap id="GAP-08" title="Refund and return execution">The dispute conversation is connected. Actual refunds and returned-payment posting require completed backend and provider workflows.</Gap></Card></div></div></>;
}
