/** Review inventory, not dynamically enabled provider capability. */
export const integrationGaps = [
  { id: 'GAP-01', title: 'Bank-transfer funding instructions', screen: '/wallet', api: 'API-005 / API-014', status: 'Partner acceptance', requirement: 'Persistent provisioning and independent verified-credit contracts now exist with an explicitly local TEST adapter. Implement and qualify the real QPay partner adapter before displaying real account details.' },
  { id: 'GAP-02', title: 'Card and USSD funding', screen: '/wallet', api: 'API-014', status: 'Decision needed', requirement: 'Choose an approved hosted collection flow and establish fees, limits, signed return/callback verification and verified wallet credit. The browser must never collect raw card security data.' },
  { id: 'GAP-03', title: 'Identity-document upload and verification', screen: '/verification', api: 'API-004 / API-031', status: 'Provider acceptance', requirement: 'Owned encrypted/scanned upload, resumable identity draft, immutable submission and independent manual review are implemented. Automatic verification/liveness, camera handoff and real scanner/storage qualification remain.' },
  { id: 'GAP-04', title: 'Verified email and phone changes', screen: '/settings/profile', api: 'API-001 / API-002', status: 'Partially resolved', requirement: 'Dual-mailbox email change with reauthentication, expiring bounded proofs, recipient invalidation and session revocation is implemented. Verified SMS/phone change remains unavailable.' },
  { id: 'GAP-05', title: 'Privacy data export', screen: '/settings/privacy', api: 'API-031', status: 'Partial API', requirement: 'Step-up profile/preferences/controls export is available and labels its scope. Complete all-record encrypted asynchronous privacy export and retention workflows remain; statements use a separate authenticated endpoint.' },
  { id: 'GAP-06', title: 'Account closure', screen: '/settings/privacy', api: 'API-001 / API-031', status: 'Backend implemented', requirement: 'Guarded zero-balance/no-pending/no-open-case closure, retained audit/history, schedule cancellation and session revocation are implemented. In-person and deployment retention/recovery acceptance remain.' },
  { id: 'GAP-07', title: 'Support attachments and inbound replies', screen: '/support', api: 'API-030 / API-031', status: 'Partial API', requirement: 'Private scanned attachments, ownership, escalation and immutable case events are implemented. Full assignment/SLA automation, conversation pagination and safe inbound email remain.' },
  { id: 'GAP-08', title: 'Dispute decisions, refunds and returns', screen: '/support/new', api: 'API-023 / API-024', status: 'Partial API', requirement: 'A customer can open a dispute case, but linked compensating financial execution, provider evidence and independent operator review remain separate backend work.' },
  { id: 'GAP-09', title: 'Original payment lookup after transport loss', screen: '/transfers/recovery', api: 'API-011 / API-019', status: 'Backend implemented', requirement: 'Owner-scoped idempotency-key/quote lookup replaces the bounded history search. A missing result never implies failure or authorises a replacement payment.' },
  { id: 'GAP-10', title: 'Complete statement and history exports', screen: '/statements', api: 'API-028', status: 'API improvement', requirement: 'Current JSON/CSV statements are bounded to 366 days and 10,000 entries. Add async jobs for larger exports and stable filters/pagination for history, funding and case messages.' },
  { id: 'GAP-11', title: 'Notification delivery and action destinations', screen: '/notifications', api: 'API-029 / NOT-009 / NOT-016', status: 'Partial API', requirement: 'Qualify the self-hosted Novu bridge and provider callbacks; align email action origins with the web app; preserve authorised destinations and implement subscribed-mail opt-out separately.' },
  { id: 'GAP-12', title: 'Recipient discovery and bill catalogue', screen: '/transfers/new', api: 'API-015 / API-020 / API-021', status: 'Partially resolved', requirement: 'Authenticated exact opt-in handles, one-off verified bank enquiries, favourites and saved bills now exist. Verified phone discovery and full live provider catalogue/pagination remain.' },
  { id: 'GAP-13', title: 'Recurring and business products', screen: '/review', api: 'API-037–042 / WEB-021', status: 'Partially approved', requirement: 'Bounded internal mandates and non-financial reminders are implemented. External bank/bill autopay, business products, cards, credit, interest products and other specialised services remain separately gated.' },
  { id: 'GAP-14', title: 'Session and browser deployment compatibility', screen: '/settings/devices', api: 'API-002 / WEB-017', status: 'Acceptance needed', requirement: 'Test actual same-site hostnames, secure cookies, CSRF restore, cross-tab refresh, revocation and expired-session recovery. The backend must not expose mobile tokens to browser clients.' },
] as const;
export const acceptanceJourneys = [
  ['UAT-01', 'Sign in, sign out and recover the session after a browser refresh', '/login'],
  ['UAT-02', 'Register, verify contact, recover password and reject an invalid code', '/register'],
  ['UAT-03', 'Review available, held and book balance; never show invented funding details', '/wallet'],
  ['UAT-04', 'Enquire bank account, save a beneficiary, review fees and approve a transfer', '/transfers/new'],
  ['UAT-05', 'Internal wallet transfer with exact recipient and quote-bound approval', '/transfers/new?type=internal'],
  ['UAT-06', 'Validate and pay an electricity bill; distinguish payment and value delivery', '/bills'],
  ['UAT-07', 'Recover the original operation after a lost response or reload', '/transfers/recovery'],
  ['UAT-08', 'Review pending, failed, expired, restricted and insufficient-funds states', '/review'],
  ['UAT-09', 'Open authoritative receipt, download statement and search history', '/activity'],
  ['UAT-10', 'Update name/preferences, enrol MFA and revoke another device', '/settings'],
  ['UAT-11', 'Create a dispute/support case and read or send a permitted reply', '/support'],
  ['UAT-12', 'Read notification, follow a protected reference and review missing API connections', '/notifications'],
  ['UAT-13', 'Use narrow-screen navigation, keyboard controls and dark appearance', '/'],
  ['UAT-14', 'Exact opt-in handle and one-off bank recipient without mandatory saving', '/transfers/new'],
  ['UAT-15', 'Private identity upload, draft reload and immutable submission', '/verification'],
  ['UAT-16', 'Actual provisioning state and no invented funding account', '/funding'],
  ['UAT-17', 'Saved household bills, token archive and service availability', '/bills/saved'],
  ['UAT-18', 'Create, pause and cancel reminders without money movement', '/calendar'],
  ['UAT-19', 'Approve bounded internal schedule and inspect occurrence history', '/calendar/schedule'],
  ['UAT-20', 'Request exact shares, partial payment, cancellation and privacy', '/requests'],
  ['UAT-21', 'Monthly insights, categories, exclusions and budgets', '/insights'],
  ['UAT-22', 'Passkey sign-in, personal freeze and sign-out everywhere', '/security-centre'],
  ['UAT-23', 'Private support evidence and escalation without fictional refund', '/support'],
  ['UAT-24', 'Dual-mailbox change, scoped export and closure blockers', '/settings/contact'],

] as const;
