import {createContext,useContext,useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import {Link,Navigate,useNavigate} from 'react-router-dom';
import QRCode from 'qrcode';
import {ShieldCheck,ArrowUpRight,LockKeyhole} from 'lucide-react';
import {api} from '@transport';
import type {User} from './types';
import {ErrorBox,Field,Form,Notice,text} from './components/ui';
const Auth=createContext<{user:User|null;loading:boolean;error:unknown;setUser:(u:User|null)=>void;logout:()=>Promise<void>}>({user:null,loading:true,error:null,setUser:()=>{},logout:async()=>{}});
export const useAuth=()=>useContext(Auth);
export function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>();useEffect(()=>{let active=true;api.restore().then(u=>{if(active)setUser(u)}).catch(e=>{if(active)setError(e)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);async function logout(){setUser(null);try{await api.logout()}catch(e){setError(new Error('Signed out of this screen. Server-side session revocation could not be confirmed; close the browser and contact security.'))}}useEffect(()=>{if(!user)return;let timeout:ReturnType<typeof setTimeout>;const reset=()=>{clearTimeout(timeout);timeout=setTimeout(()=>{void logout()},15*60*1000)};reset();window.addEventListener('pointerdown',reset);window.addEventListener('keydown',reset);return()=>{clearTimeout(timeout);window.removeEventListener('pointerdown',reset);window.removeEventListener('keydown',reset)}},[user?.id]);return <Auth.Provider value={{user,loading,error,setUser,logout}}>{children}</Auth.Provider>}
function AuthShell({children}:{children:ReactNode}){const [theme,setTheme]=useState('split');return <main className={'auth-shell auth-'+theme}><section className="auth-story"><Link className="brand" to="/login"><span className="brand-mark">Q</span>qpay<span className="brand-tag">OPERATIONS</span></Link><div><span className="eyebrow">Clarity. Control. Accountability.</span><h1>Every movement.<br/>Every decision.<br/><em>In clear view.</em></h1><p>A dedicated workspace for the people who keep Qpay running. Secure access, independent oversight, and a record of every action.</p></div><div className="auth-assurance"><ShieldCheck/><span>Staff-only access · Mandatory MFA<br/>No direct balance editing</span></div></section><section className="auth-panel"><div className="auth-options"><span>{__ADMIN_REVIEW__?'SYNTHETIC REVIEW':'STAFF ACCESS'}</span><label>Layout <select value={theme} onChange={e=>setTheme(e.target.value)}><option value="split">Split</option><option value="centred">Centred</option><option value="minimal">Minimal</option></select></label></div><div className="auth-card">{children}</div><footer>Protected staff workspace. Do not share credentials or customer information.</footer></section></main>}
export function LoginPage(){const {user,setUser,error}=useAuth(),nav=useNavigate();if(user)return <Navigate to={user.mfa_enabled?'/':'/enrol'} replace/>;return <AuthShell><div className="auth-icon"><LockKeyhole/></div><h2>Welcome back.</h2><p className="muted">Sign in to your operations workspace.</p><ErrorBox error={error}/>{__ADMIN_REVIEW__&&<Notice>Synthetic review only. Accounts: <b>admin</b>, <b>checker</b>, finance, compliance, support, platform, auditor or enrol @review.example.invalid. Password: <code>Admin-review-only-2026!</code>. MFA: <code>123456</code>. No real transactions.</Notice>}<Form submit="Sign in securely" onSubmit={async f=>{const s=await api.login({email:text(f,'email'),password:String(f.get('password')),mfa_code:text(f,'mfa_code'),recovery_code:text(f,'recovery_code'),client:'web',device:'Qpay operations browser'});setUser(s.user);nav(s.mfa_enrolment_required?'/enrol':'/')}}><Field name="email" label="Work email" type="email"/><Field name="password" label="Password" type="password"/><Field name="mfa_code" label="Authenticator code" required={false} help="Required when MFA is already enrolled."/><details><summary>Use an MFA recovery code instead</summary><Field name="recovery_code" label="Recovery code" required={false}/></details></Form><div className="auth-links"><Link to="/accept-invite">Accept a staff invitation <ArrowUpRight size={14}/></Link><Link to="/access-help">Need help with access?</Link></div></AuthShell>}
export function EnrolPage(){const {user,setUser}=useAuth();const nav=useNavigate();const [enrol,setEnrol]=useState<{secret:string;otpauth_url:string}|null>(null),[qr,setQR]=useState(''),[codes,setCodes]=useState<string[]>([]);if(!user)return <Navigate to="/login" replace/>;return <AuthShell><h2>Secure your account</h2><p>Enrol an authenticator before accessing any operational records.</p>{!enrol&&!codes.length&&<Form submit="Begin MFA enrolment" onSubmit={async f=>{const result=await api.request<{secret:string;otpauth_url:string}>('POST','/v1/admin/auth/mfa/enrol',{password:String(f.get('password')),mfa_code:text(f,'mfa_code')});setEnrol(result);setQR(await QRCode.toDataURL(result.otpauth_url,{margin:2,width:220}))}}><Field name="password" label="Confirm password" type="password"/><Field name="mfa_code" label="Current MFA code (when replacing)" required={false}/></Form>}{enrol&&!codes.length&&<><img className="qr" src={qr} alt="Authenticator enrolment QR code"/><details><summary>Use the manual setup key</summary><code className="secret">{enrol.secret}</code></details><Form submit="Verify authenticator" onSubmit={async f=>{setCodes(await api.request<string[]>('POST','/v1/admin/auth/mfa/confirm',{code:text(f,'code')}));setEnrol(null);setQR('')}}><Field name="code" label="Six-digit code"/></Form></>}{codes.length>0&&<><Notice>Save these recovery codes privately. They will not be shown again. Each is single-use.</Notice><div className="recovery-codes">{codes.map(c=><code key={c}>{c}</code>)}</div><button className="button primary" onClick={()=>{setCodes([]);setUser({...user,mfa_enabled:true});nav('/')}}>I have stored my recovery codes</button>{user.mfa_enabled&&<Navigate to="/" replace/>}</>}{user.mfa_enabled&&codes.length===0&&!enrol&&<Link to="/">Continue to operations</Link>}</AuthShell>}
export function InvitePage(){const [done,setDone]=useState(false);return <AuthShell><h2>Join the operations team</h2><p>An independently approved invitation is required. Enter the private token received through your organisation’s authorised channel.</p>{done?<Notice success>Invitation accepted. Sign in and complete MFA enrolment. <Link to="/login">Go to sign in</Link></Notice>:<Form submit="Accept invitation" onSubmit={async f=>{if(f.get('password')!==f.get('confirm'))throw new Error('Passwords must match');await api.request('POST','/v1/admin/invitations/accept',{token:text(f,'token'),password:String(f.get('password'))});setDone(true)}}><Field name="token" label="Private invitation token" type="password"/><Field name="password" label="Choose password" type="password" help="Use a strong unique password of at least 12 characters."/><Field name="confirm" label="Confirm password" type="password"/></Form>}<Link to="/login">Back to sign in</Link></AuthShell>}
export function AccessHelp(){return <AuthShell><h2>Recover access safely</h2><p>When your password still works, use one of your saved single-use MFA recovery codes on the sign-in screen.</p><Notice>For a lost password or lost MFA and recovery codes, contact your authorised security administrator. Staff recovery requires two eligible administrators, neither of whom is the subject. There is no public staff registration or insecure email-only reset. <Link to="/recover-access">Use an approved recovery token</Link></Notice><Link className="button primary" to="/login">Return to sign in</Link></AuthShell>}

export function RecoveryPage(){const [done,setDone]=useState(false);return <AuthShell><h2>Restore staff credentials</h2><p>Use the private, one-time token issued after independent identity checks. Recovery does not restore a suspended role or grant new permissions.</p>{done?<Notice success>Password replaced and previous sessions revoked. Sign in with the new password and enrol MFA. <Link to="/login">Return to sign in</Link></Notice>:<Form submit="Replace credentials securely" onSubmit={async f=>{if(f.get('password')!==f.get('confirm'))throw new Error('Passwords must match');await api.request('POST','/v1/admin/recovery/accept',{token:text(f,'token'),password:String(f.get('password'))});setDone(true)}}><Field name="token" label="Approved recovery token" type="password"/><Field name="password" label="New password" type="password"/><Field name="confirm" label="Repeat new password" type="password"/><Notice>Tokens expire after one hour and are bound to the approved staff version. Old authenticator and recovery codes are invalidated.</Notice></Form>}<Link to="/login">Back to sign in</Link></AuthShell>}
