import type {Bootstrap,LoginInput,Page,Row,Session,Transport,User,Role} from './types';
import {APIError} from './errors';
import {modules} from './modules';
const now=()=>new Date().toISOString();
const future=()=>new Date(Date.now()+86400000).toISOString();
export const REVIEW_PASSWORD='Admin-review-only-2026!';
export const reviewRoles:Role[]=['admin','finance','compliance','support','platform','auditor'];
const roles:Record<string,Role[]>={customers:['admin','finance','compliance','support','auditor'],staff:['admin','auditor'],invitations:['admin','auditor'],payments:['admin','finance','compliance','support','auditor'],kyc:['admin','compliance','auditor'],proposals:['admin','finance','compliance','auditor'],controls:['admin','platform','auditor'],support:['admin','support'],jobs:['admin','platform','finance','auditor'],notifications:['admin','platform','auditor'],audit:['admin','compliance','auditor'],reconciliations:['admin','finance','auditor'],exceptions:['admin','finance','auditor'],ledger:['admin','finance','auditor'],treasury:['admin','finance','auditor'],funding:['admin','finance','support','auditor'],schedules:['admin','finance','support','auditor'],requests:['admin','support','compliance','auditor'],reminders:['admin','support','auditor'],risk:['admin','compliance'],incidents:['admin','platform','auditor'],investigations:['admin','finance','auditor'],privacy:['admin','compliance','auditor'],products:['admin','platform','finance','auditor'],availability:['admin','platform','support','auditor'],exports:['admin','finance','compliance','auditor']};
const actionRoles:Record<string,Role[]>={note:['admin','finance','compliance','support','platform'],work_create:['admin','finance','compliance','platform'],work_update:['admin','finance','compliance','platform'],support_assign:['admin','support'],customer_sessions_revoke:['admin','compliance'],schedule_stop:['admin','compliance'],notification_suppress:['admin','platform'],emergency_stop:['admin','platform'],control_propose:['admin','platform'],control_decide:['admin','platform'],invite_propose:['admin'],invite_decide:['admin'],invite_revoke:['admin']};
const uid=(role:Role)=>'usr_review_'+role;
function seed():Record<string,Row[]>{
 const at=now();const tables:Record<string,Row[]>={};for(const m of modules)tables[m.id]=[];
 tables.customers=[{id:'usr_customer_02',name:'Ada Okoro',email:'a***@example.invalid',status:'active',role:'customer',tier:2,mfa_enabled:true,version:1,created_at:at},{id:'usr_customer_01',name:'Tunde Bello',email:'t***@example.invalid',status:'restricted',role:'customer',tier:1,mfa_enabled:false,version:2,created_at:at}];
 tables.staff=reviewRoles.map(role=>({id:uid(role),name:`Review ${role}`,email:`${role}@review.example.invalid`,role,status:'active',mfa_enabled:true,version:1,created_at:at}));tables.staff.push({id:'usr_review_checker',name:'Review checker',email:'checker@review.example.invalid',role:'admin',status:'active',mfa_enabled:true,version:1,created_at:at});
 tables.payments=[{id:'pay_review_bank',owner_id:'usr_customer_02',recipient_id:null,kind:'bank',status:'pending',amount_minor:'2500000',fee_minor:'5000',total_minor:'2505000',currency:'NGN',narration:'Supplier payment',provider_reference:'SYNTHETIC-001',fulfilment_status:'not_applicable',created_at:at},{id:'pay_review_bill',owner_id:'usr_customer_02',kind:'bill',status:'succeeded',amount_minor:'1500000',fee_minor:'0',total_minor:'1500000',currency:'NGN',narration:'Home electricity',provider_reference:'SYNTHETIC-002',fulfilment_status:'pending',created_at:at},{id:'pay_review_internal',owner_id:'usr_customer_02',recipient_id:'usr_customer_01',kind:'internal',status:'succeeded',amount_minor:'800000',fee_minor:'0',total_minor:'800000',currency:'NGN',narration:'Household contribution',fulfilment_status:'not_applicable',created_at:at}];
 tables.kyc=[{id:'kyc_review_01',owner_id:'usr_customer_02',name:'Ada Okoro',status:'submitted',tier:2,version:1,document_count:0,created_at:at}];
 tables.jobs=[{id:'job_review_01',object_id:'pay_review_bank',status:'dead',attempts:20,last_error:'Original reference requires investigation',available_at:at,created_at:at}];
 tables.proposals=[{id:'prop_review_01',maker_id:uid('finance'),action:'policy',target:'payment-policy',target_version:1,payload:{policy:{per_payment_minor:'10000000',daily_minor:'50000000',internal_fee_minor:'0',payments_enabled:false}},reason:'Review proposed transaction policy',status:'pending',expires_at:future(),created_at:at}];
 tables.products=[{id:'synthetic-electricity',enabled:true,version:1,updated_at:at}];tables.availability=[{id:'synthetic-electricity',status:'unknown',observed_at:at,version:1}];
 tables.funding=[{id:'fundacct_review_01',owner_id:'usr_customer_02',provider:'synthetic-local',provider_ref:'SYNTHETIC-ACCOUNT',status:'active',updated_at:at}];
 tables.ledger=[{id:'journal_review_01',reference:'pay_review_internal',kind:'internal_transfer',currency:'NGN',created_at:at}];tables.treasury=[{id:'wallet:usr_customer_02',kind:'wallet',owner_id:'usr_customer_02',currency:'NGN',balance_minor:'97500000',held_minor:'2505000',available_minor:'94995000'},{id:'house:fees',kind:'revenue',currency:'NGN',balance_minor:'55000',held_minor:'0',available_minor:'55000'},{id:'house:clearing',kind:'clearing',currency:'NGN',balance_minor:'-97555000',held_minor:'0',available_minor:'-97555000'}];
 tables.support=[{id:'case_review_01',owner_id:'usr_customer_02',payment_id:'pay_review_bank',kind:'complaint',subject:'Transfer still pending',issue_type:'money-not-received',status:'open',assigned_to:null,response_due_at:future(),version:1,created_at:at}];
 tables.reconciliations=[{id:'recon_review_01',source:'provider',actor_id:uid('finance'),row_count:2,exceptions:1,created_at:at}];tables.exceptions=[{id:'break_review_01',run_id:'recon_review_01',reference:'pay_review_bank',amount_minor:'2500000',currency:'NGN',status:'pending',reason:'not_final_success',created_at:at}];
 tables.notifications=[{id:'notice_review_01',owner_id:'usr_customer_02',workflow:'transfer-pending',reference:'pay_review_bank',status:'queued',attempts:0,expires_at:future(),created_at:at}];
 tables.schedules=[{id:'mandate_review_01',owner_id:'usr_customer_02',title:'Family allowance',cadence:'monthly',status:'active',next_at:future(),ends_at:future(),occurrences:1,max_occurrences:12,max_debit_minor:'800000',max_total_minor:'9600000',committed_minor:'800000',version:1,created_at:at}];
 tables.requests=[{id:'request_review_01',owner_id:'usr_customer_02',amount_minor:'2400000',currency:'NGN',memo:'Shared household costs',status:'open',expires_at:future(),created_at:at}];tables.reminders=[{id:'reminder_review_01',owner_id:'usr_customer_02',title:'Renew internet',cadence:'monthly',status:'active',due_at:future(),version:1,created_at:at}];
 tables.risk=[{id:'work_risk_review',kind:'risk',subject:'Review reported unusual activity',target:'usr_customer_01',severity:'high',status:'open',assigned_to:null,created_by:uid('compliance'),version:1,due_at:future(),created_at:at}];tables.incidents=[{id:'work_incident_review',kind:'incident',subject:'Upstream status confirmation delayed',target:'payment-gateway',severity:'medium',status:'investigating',assigned_to:uid('platform'),version:1,due_at:future(),created_at:at}];tables.investigations=[{id:'work_finance_review',kind:'exception',subject:'Investigate unsettled provider record',target:'break_review_01',severity:'medium',status:'open',assigned_to:null,version:1,due_at:future(),created_at:at}];tables.privacy=[{id:'closure_review_01',owner_id:'usr_customer_01',status:'pending',created_at:at}];
 tables.audit=[{id:'audit_review_01',actor:uid('admin'),action:'admin.session_opened',target:'operations',details:{synthetic:true},created_at:at}];return tables;
}
export class ReviewAPI implements Transport{
 private user:User|null=null;private tables=seed();private notes:Record<string,Row[]>={};private messages:Record<string,Row[]>={'case_review_01':[{id:'msg_review_01',author_id:'usr_customer_02',message:'Please help me check the original transfer.',created_at:now()}]};private policy={version:1,per_payment_minor:'10000000',daily_minor:'50000000',internal_fee_minor:'0',payments_enabled:true};private serial=0;private recoveryTokens=new Map<string,string>();private invitationTokens=new Map<string,string>();
 private id(prefix:string){return `${prefix}_review_${String(++this.serial).padStart(5,'0')}`}
 private fail(status:number,message:string):never{throw new APIError(status,status===403?'forbidden':'conflict',message,'synthetic-request')}
 private actor(){if(!this.user)this.fail(401,'Sign in to the synthetic review');return this.user}
 async restore(){return structuredClone(this.user)}
 async login(input:LoginInput):Promise<Session>{const role=input.email.split('@')[0];if(input.password!==REVIEW_PASSWORD||input.mfa_code!=='123456'||(!reviewRoles.includes(role as Role)&&role!=='checker'&&role!=='enrol'))this.fail(401,'Use a documented synthetic account, review password and code 123456');this.user={id:role==='checker'?'usr_review_checker':uid(role==='enrol'?'support':role as Role),email:input.email,name:role==='checker'?'Review checker':`Review ${role}`,role:role==='checker'?'admin':role==='enrol'?'support':role as Role,status:'active',mfa_enabled:role!=='enrol',version:1};return {user:structuredClone(this.user),mfa_enrolment_required:!this.user.mfa_enabled}}
 async logout(){this.user=null}
 async blob(path:string,body:unknown):Promise<Blob>{if(path.endsWith('/exports')){if(!['admin','finance','compliance','auditor'].includes(this.actor().role))this.fail(403,'Export role required');const b=body as {resource:string;search:string;reason:string};if(b.reason.length<8)this.fail(400,'Export reason required');const page=await this.request<Page>('GET',`/v1/admin/console/records/${b.resource}?search=${encodeURIComponent(b.search)}`);const keys=Object.keys(page.items[0]||{});const text=[keys.join(','),...page.items.map(row=>keys.map(k=>'"'+String(row[k]??'').replaceAll('"','""')+'"').join(','))].join('\n');this.tables.exports.unshift({id:this.id('export'),actor_id:this.actor().id,resource:b.resource,reason:b.reason,row_count:page.items.length,created_at:now()});return new Blob([text],{type:'text/csv'})};this.fail(503,'No private document exists in this review fixture')}
 async request<T=Row>(method:string,path:string,body?:unknown):Promise<T>{
 const url=new URL(path,'https://review.invalid');let p=url.pathname;p=p.replace('/console/proposals/','/proposals/').replace('/console/payments/','/payments/');const b=(body||{}) as Record<string,unknown>;if(b.decision==='approve')b.approve=true;if(b.decision==='reject')b.approve=false;let out:unknown;
 if(p==='/v1/admin/recovery/accept'){const owner=this.recoveryTokens.get(String(b.token));if(!owner)this.fail(401,'Invalid synthetic recovery token');this.recoveryTokens.delete(String(b.token));return {status:'accepted',mfa_reenrolment_required:true} as T}
 if(p==='/v1/admin/invitations/accept'){const invite=this.tables.invitations.find(i=>i.id===this.invitationTokens.get(String(b.token))&&i.status==='approved');if(!invite)this.fail(401,'Invalid synthetic invitation');invite.status='accepted';delete invite.token;return {id:this.id('usr')} as T}
 const u=this.actor();if(!u.mfa_enabled&&!p.startsWith('/v1/admin/auth/'))this.fail(403,'Complete MFA enrolment');
 if(p.endsWith('/auth/me'))out=u;
 else if(p.endsWith('/auth/elevate')){if(b.password!==REVIEW_PASSWORD||b.mfa_code!=='123456')this.fail(401,'Invalid review proof');out={status:'accepted'}}
 else if(p.endsWith('/mfa/enrol'))out={secret:'JBSWY3DPEHPK3PXP',otpauth_url:'otpauth://totp/Synthetic?secret=JBSWY3DPEHPK3PXP&issuer=QpayReview'};
 else if(p.endsWith('/mfa/confirm')){if(b.code!=='123456')this.fail(401,'Review code is 123456');u.mfa_enabled=true;out=Array.from({length:10},(_,i)=>'synthetic-recovery-'+i)}
 else if(p.endsWith('/auth/password')){if(b.password!==REVIEW_PASSWORD||b.mfa_code!=='123456')this.fail(401,'Invalid review proof');this.user=null;out={status:'accepted'}}
 else if(p.includes('/auth/sessions'))out=method==='GET'?[{id:'session_review',device:'This synthetic browser',current:true,revoked:false,created_at:now(),expires_at:future()}]:undefined;
 else if(p.endsWith('/console/bootstrap'))out={user:u,resources:Object.keys(roles).filter(k=>roles[k].includes(u.role)),actions:Object.keys(actionRoles).filter(k=>actionRoles[k].includes(u.role)),environment:'review',synthetic_execution:true,server_time:now(),external_execution_configured:false,notification_mode:'synthetic-review',schedules_configured:true,private_storage_configured:false,scanner_configured:false,live_acceptance:false,gates:['Synthetic in-memory review; no real accounts or payments','QPay live execution not enabled','Refund/return execution unavailable','Bank float and settlement not verified','Novu live delivery acceptance required']} satisfies Bootstrap;
 else if(p.endsWith('/console/metrics'))out={customers:2,pending_payments:1,open_support:this.tables.support.filter(r=>r.status!=='resolved').length,kyc_waiting:1,approvals:this.tables.proposals.filter(r=>r.status==='pending').length,dead_jobs:this.tables.jobs.filter(r=>r.status==='dead').length,exceptions:1,payments_enabled:this.policy.payments_enabled,generated_at:now(),scope:'Synthetic review snapshot; no real custody, funds or settlement.',...(['admin','finance','auditor'].includes(u.role)?{ledger:{currency:'NGN',wallet_liability_minor:'97500000',held_minor:'2505000',fee_income_minor:'55000',clearing_minor:'-97555000',unbalanced_journals:0}}:{})};
 else if(p.includes('/console/records/')){const [resource,id]=p.split('/console/records/')[1].split('/').map(decodeURIComponent);if(!roles[resource]?.includes(u.role))this.fail(403,'Your role cannot access this module');let items=this.tables[resource];if(resource==='proposals'&&u.role!=='admin'&&u.role!=='auditor')items=items.filter(r=>u.role==='finance'?r.action==='policy':r.action!=='policy');if(resource==='controls'&&u.role==='platform')items=items.filter(r=>['product','resume'].includes(String(r.kind)));
  if(id){const record=items.find(r=>r.id===id);if(!record)this.fail(404,'Record not found');const related:Record<string,unknown>={notes:this.notes[resource+id]||[]};if(resource==='customers')related.wallet=this.tables.treasury.filter(r=>r.owner_id===id);if(resource==='payments'){related.observations=[{status:record.status,amount_minor:record.amount_minor,currency:'NGN',created_at:now()}];related.holds=record.status==='pending'?[{status:'active',amount_minor:record.total_minor}]:[];related.jobs=this.tables.jobs.filter(r=>r.object_id===id);related.journals=this.tables.ledger.filter(r=>r.reference===id)}if(resource==='ledger')related.postings=[{id:'1',account_id:'wallet:usr_customer_02',delta_minor:'-800000'},{id:'2',account_id:'wallet:usr_customer_01',delta_minor:'800000'}];if(resource==='support'){related.events=[{event:'case_opened',created_at:now()}];related.documents=[]}if(resource==='kyc')related.documents=[];if(resource==='reconciliations')related.items=this.tables.exceptions.filter(r=>r.run_id===id);if(resource==='schedules')related.occurrences=[{id:'occ_review',status:'submitted',payment_id:'pay_review_internal',due_at:now()}];if(resource==='requests')related.shares=[{id:'share_review',payer_id:'usr_customer_01',amount_minor:'2400000',received_minor:'0',status:'open'}];if(resource==='notifications')related.events=[];out={record,...related}}
  else{const q=(url.searchParams.get('search')||'').toLowerCase();const before=url.searchParams.get('before')||'';const n=Number(url.searchParams.get('limit')||50);const sorted=items.filter(r=>(!before||String(r.id)<before)&&JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>String(b.id).localeCompare(String(a.id)));const visible=sorted.slice(0,n);out={items:visible,has_more:sorted.length>n,next_before:sorted.length>n?visible.at(-1)?.id:'',generated_at:now()}}
 }
 else if(p==='/v1/admin/console/payment-control'){if(!['admin','platform'].includes(u.role))this.fail(403,'Control role required');out={version:this.policy.version,payments_enabled:this.policy.payments_enabled}}
 else if(p==='/v1/admin/policy'){if(!['admin','finance','compliance'].includes(u.role))this.fail(403,'Policy role required');out=this.policy}
 else if(p==='/v1/admin/proposals'&&method==='POST'){const policy=b.action==='policy';if(!(policy?['admin','finance']:['admin','compliance']).includes(u.role))this.fail(403,'Proposal role required');const id=this.id('prop');this.tables.proposals.unshift({id,maker_id:u.id,action:String(b.action),target:String(b.target||'payment-policy'),target_version:this.policy.version,payload:b as Row,reason:String(b.reason),status:'pending',expires_at:future(),created_at:now()});out={id}}
 else if(p.match(/\/proposals\/[^/]+\/decision$/)){const proposal=this.tables.proposals.find(r=>r.id===p.split('/').at(-2));if(!proposal||proposal.status!=='pending')this.fail(409,'Proposal changed');if(proposal.maker_id===u.id)this.fail(403,'A different eligible operator must decide');if(!(proposal.action==='policy'?['admin','finance']:['admin','compliance']).includes(u.role))this.fail(403,'Approver role required');if(b.approve&&proposal.action==='policy'){if(proposal.target_version!==this.policy.version)this.fail(409,'Policy changed');const payload=proposal.payload as Row;this.policy={...this.policy,...(payload.policy as object),version:this.policy.version+1}}proposal.status=b.approve?'approved':'rejected';proposal.checker_id=u.id;out={status:'accepted'}}
 else if(p.match(/\/payments\/[^/]+\/requery$/)){if(!['admin','finance','platform'].includes(u.role))this.fail(403,'Recovery role required');const job=this.tables.jobs.find(r=>r.object_id===p.split('/').at(-2));if(!job||job.status!=='dead')this.fail(409,'Job is not awaiting retry');job.status='queued';out={status:'accepted'}}
 else if(p.includes('/support/cases/')&&p.endsWith('/messages')){if(!['admin','support'].includes(u.role))this.fail(403,'Support role required');const id=p.split('/').at(-2)!;if(method==='POST'){(this.messages[id]??=[]).push({id:this.id('msg'),author_id:u.id,message:String(b.message),created_at:now()});const record=this.tables.support.find(r=>r.id===id);if(record&&b.status)record.status=String(b.status);out={status:'accepted'}}else out=this.messages[id]||[]}
 else if(p==='/v1/admin/reconciliations'&&method==='POST'){if(!['admin','finance'].includes(u.role))this.fail(403,'Finance role required');const entries=b.entries as Row[];if(!entries?.length||new Set(entries.map(r=>r.reference)).size!==entries.length)this.fail(400,'Unique reconciliation entries required');const id=this.id('recon');const results=entries.map(r=>{const pay=this.tables.payments.find(p=>p.id===r.reference);const matched=pay?.status==='succeeded'&&pay.amount_minor===r.amount_minor&&r.status==='succeeded';if(!matched)this.tables.exceptions.push({id:this.id('break'),run_id:id,...r,reason:'evidence_mismatch',created_at:now()});return {reference:r.reference,matched,reason:matched?'matched':'evidence_mismatch'}});this.tables.reconciliations.push({id,source:String(b.source),row_count:entries.length,exceptions:results.filter(r=>!r.matched).length,created_at:now()});out={id,results,scope:'Synthetic imported rows only; no settlement completeness claim'}}
 else if(p.endsWith('/fulfilment')){if(!['admin','support'].includes(u.role))this.fail(403,'Evidence role required');const payment=this.tables.payments.find(r=>r.id===p.split('/').at(-2));if(!payment||payment.kind!=='bill')this.fail(404,'Bill not found');out={status:payment.fulfilment_status,payment_status:payment.status,...(payment.fulfilment_status==='ready'?{value:'SYNTHETIC TOKEN ONLY'}:{})}}
 else if(p==='/v1/admin/console/biller-observation'){if(!['admin','platform'].includes(u.role))this.fail(403,'Observation role required');this.tables.availability=this.tables.availability.filter(r=>r.id!==b.product_id);this.tables.availability.unshift({id:String(b.product_id),status:String(b.status),observed_at:now(),version:1});out={status:'accepted'}}
 else if(p.endsWith('/console/catalogue'))out=[{id:'synthetic-electricity',name:'Synthetic Electricity',category:'electricity',variable:true}];
 else if(p==='/v1/admin/console/invitations'){if(u.role!=='admin')this.fail(403,'Administrator required');const id=this.id('invite');this.tables.invitations.unshift({id,email:String(b.email),name:String(b.name),role:String(b.role),maker_id:u.id,status:'proposed',reason:String(b.reason),expires_at:future(),created_at:now()});out={id}}
 else if(p.match(/\/console\/invitations\/[^/]+\/decision$/)){if(u.role!=='admin')this.fail(403,'Administrator required');const i=this.tables.invitations.find(r=>r.id===p.split('/').at(-2));if(!i||!['proposed','approved'].includes(String(i.status)))this.fail(409,'Invitation changed');if(b.decision!=='revoke'&&i.maker_id===u.id)this.fail(403,'Another administrator must decide');i.status=b.decision==='approve'?'approved':b.decision==='reject'?'rejected':'revoked';i.checker_id=u.id;if(b.decision==='approve'){this.invitationTokens.set('SYNTHETIC_INVITE_TOKEN',String(i.id));out={status:'approved',invitation_token:'SYNTHETIC_INVITE_TOKEN',expires_at:i.expires_at,delivery:'Synthetic token only'}}else out={status:i.status}}
 else if(p==='/v1/admin/console/actions'){const action=String(b.action);if(!actionRoles[action]?.includes(u.role))this.fail(403,'Action not permitted');if(String(b.reason).trim().length<8)this.fail(400,'Explain the action in at least eight characters');const target=String(b.target);const resource=String(b.resource);const record=this.tables[resource]?.find(r=>r.id===target);
  if(action==='note'){if(!roles[resource]?.includes(u.role)||!record)this.fail(403,'Record not permitted');(this.notes[resource+target]??=[]).unshift({id:this.id('note'),actor_id:u.id,message:String(b.reason),created_at:now()})}
  else if(action==='emergency_stop'){if(b.version!==this.policy.version)this.fail(409,'Policy changed');this.policy.payments_enabled=false;this.policy.version++}
  else if(action==='work_create'){const bucket=resource==='risk'?'risk':resource==='incident'?'incidents':'investigations';if(!roles[bucket].includes(u.role))this.fail(403,'Investigation role required');const id=this.id('work');this.tables[bucket].unshift({id,kind:resource,subject:String(b.title),target,severity:String(b.severity),status:'open',version:1,due_at:future(),created_at:now()});out={id,financial_effect:false}}
  else if(action==='work_update'){const r=[...this.tables.risk,...this.tables.incidents,...this.tables.investigations].find(r=>r.id===target);if(!r||r.version!==b.version||r.status==='resolved')this.fail(409,'Work item changed');const bucket=r.kind==='risk'?'risk':r.kind==='incident'?'incidents':'investigations';if(!roles[bucket].includes(u.role))this.fail(403,'Investigation role required');r.status=String(b.value);r.assigned_to=String(b.assigned_to||'');r.version=Number(r.version)+1}
  else if(action==='support_assign'){const r=this.tables.support.find(r=>r.id===target);if(!r||r.version!==b.version)this.fail(409,'Case changed');r.assigned_to=String(b.assigned_to);r.version=Number(r.version)+1}
  else if(action==='schedule_stop'){const r=this.tables.schedules.find(r=>r.id===target);if(!r||r.version!==b.version||r.status!=='active')this.fail(409,'Mandate changed');r.status='paused';r.version=Number(r.version)+1}
  else if(action==='notification_suppress'){const r=this.tables.notifications.find(r=>r.id===target);if(!r||!['queued','dead'].includes(String(r.status)))this.fail(409,'Notice is no longer cancellable');r.status='suppressed'}
  else if(action==='control_propose'){if(['staff_role','staff_status','staff_recovery'].includes(resource)&&(u.role!=='admin'||target===u.id))this.fail(403,'Administrator required');const id=this.id('control');this.tables.controls.unshift({id,kind:resource,target,value:String(b.value),target_version:Number(b.version),maker_id:u.id,reason:String(b.reason),status:'pending',expires_at:future(),created_at:now()});out={id}}
  else if(action==='control_decide'){const c=this.tables.controls.find(r=>r.id===target);if(!c||c.status!=='pending')this.fail(409,'Control changed');if(c.maker_id===u.id||c.target===u.id)this.fail(403,'Independent review required');if(!['product','resume'].includes(String(c.kind))&&u.role!=='admin')this.fail(403,'Administrator required');if(b.value==='approve'){if(c.kind==='staff_recovery'){this.recoveryTokens.set('SYNTHETIC_RECOVERY_TOKEN',String(c.target));out={recovery_token:'SYNTHETIC_RECOVERY_TOKEN',expires_at:future(),delivery:'Synthetic recovery review only'}}else if(c.kind==='resume'){if(c.target_version!==this.policy.version)this.fail(409,'Policy changed');this.policy.payments_enabled=true;this.policy.version++}else{const r=this.tables[c.kind==='product'?'products':'staff'].find(r=>r.id===c.target);if(!r||r.version!==c.target_version)this.fail(409,'Target changed');if(c.kind==='product')r.enabled=c.value==='enabled';else if(c.kind==='staff_role')r.role=c.value;else r.status=c.value;r.version=Number(r.version)+1}}c.status=b.value==='approve'?'approved':'rejected';c.checker_id=u.id}
  else if(action!=='customer_sessions_revoke')this.fail(400,'Unsupported synthetic command');out??={status:'recorded'};this.tables.audit.unshift({id:this.id('audit'),actor:u.id,action:'admin.'+action,target,details:{reason:String(b.reason)},created_at:now()})
 }
 else if(p.includes('/console/identity/')){if(!['admin','compliance'].includes(u.role))this.fail(403,'Identity role required');out={identity:{legal_name:'Ada Okoro',date_of_birth:'1990-01-01',address:'Synthetic review address'},owner_id:'usr_customer_02'}}
 else this.fail(503,'This operation is not implemented in the review adapter');
 return structuredClone(out) as T;
 }
}
export const api=new ReviewAPI();
