import {useState} from 'react';
import {api} from '@transport';
import type {Row} from '../types';
import {DataTable,Field,Form,Notice,text} from '../components/ui';
export interface ImportRow {reference:string;amount_minor:string;currency:string;status:string}
// Deliberately supports a documented four-field CSV subset rather than guessing provider formats.
export function parseImport(value:string):ImportRow[]{
 if(value.length>800000)throw new Error('File exceeds 800 KB');
 const lines=value.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.shift()?.trim()!=='reference,amount_minor,currency,status')throw new Error('Required header: reference,amount_minor,currency,status');
 if(!lines.length||lines.length>2000)throw new Error('Import 1–2,000 rows at a time');
 const seen=new Set<string>();return lines.map((line,index)=>{const fields=line.split(',').map(v=>v.trim());if(fields.length!==4||fields.some(v=>v.includes('"')))throw new Error(`Row ${index+2}: use four unquoted fields without embedded commas`);const [reference,amount_minor,currency,status]=fields;
 if(!/^[A-Za-z0-9_-]{8,100}$/.test(reference)||seen.has(reference))throw new Error(`Row ${index+2}: invalid or duplicate reference`);seen.add(reference);
 if(!/^(0|[1-9]\d{0,15})$/.test(amount_minor)||(BigInt(amount_minor)<1n||BigInt(amount_minor)>9000000000000000n)||currency!=='NGN'||!['succeeded','failed','pending'].includes(status))throw new Error(`Row ${index+2}: invalid minor-unit amount, currency or status`);
 return {reference,amount_minor,currency,status};});
}
export function ReconciliationImport({onDone}:{onDone:()=>void}){const [rows,setRows]=useState<ImportRow[]>([]),[value,setValue]=useState('reference,amount_minor,currency,status\n'),[result,setResult]=useState<Row|null>(null),[error,setError]=useState('');return <><Notice>Import independently obtained provider observations. This comparison neither moves money nor certifies a complete bank/provider/ledger reconciliation. A mismatch must be investigated.</Notice><div className="field"><label htmlFor="recon-file">Upload normalised CSV</label><input id="recon-file" type="file" accept=".csv,text/csv" onChange={async e=>{setRows([]);setResult(null);const file=e.target.files?.[0];if(file){if(file.size>800000){setError('File exceeds 800 KB');return}setValue(await file.text());setError('')}}}/></div><div className="field"><label htmlFor="csv-data">CSV content</label><textarea id="csv-data" rows={6} value={value} onChange={e=>{setValue(e.target.value);setRows([]);setResult(null)}} spellCheck={false}/><small>Amounts are integer minor-unit strings. No quoted or multiline fields. Maximum 2,000 rows.</small></div><button className="button" onClick={()=>{try{setRows(parseImport(value));setError('');setResult(null)}catch(e){setError((e as Error).message)}}}>Validate and preview</button>{error&&<div className="notice error" role="alert">{error}</div>}{rows.length>0&&<><h3>{rows.length} validated records</h3><DataTable items={rows.slice(0,10) as unknown as Row[]} columns={['reference','amount_minor','currency','status']} caption="Import preview (first 10 records)"/><Form submit="Compare imported observations" onSubmit={async f=>{setResult(await api.request('POST','/v1/admin/reconciliations',{source:text(f,'source'),entries:rows}));setRows([]);onDone()}}><Field name="source" label="Independent source" options={[["provider","Provider observations"],["bank","Bank observations"]]}/></Form></>}{result&&<><Notice success>Comparison stored as {String(result.id)}. No financial effect.</Notice><DataTable items={(result.results||[]) as Row[]} columns={['reference','matched','reason']} caption="Comparison results"/></>}</>}
