import {describe,it,expect} from 'vitest';
import {ReviewTransport,reviewCredentials} from '../src/review/transport';
import {splitMinor,watISO,watInput,localMonth} from '../src/api/parity';
import {encodeBase64URL,decodeBase64URL} from '../src/api/passkeys';
import type {Controls,SavedBill,Reminder,RequestDetail,Insights} from '../src/api/parity';
import type {Quote,Approval,Payment,Wallet} from '../src/api/types';
class Memory implements Storage {map=new Map<string,string>();get length(){return this.map.size}clear(){this.map.clear()}getItem(k:string){return this.map.get(k)??null}key(i:number){return [...this.map.keys()][i]??null}removeItem(k:string){this.map.delete(k)}setItem(k:string,v:string){this.map.set(k,v)}}
async function setup(){const storage=new Memory(),api=new ReviewTransport(storage);await api.request('POST','/v1/auth/login',{body:{email:reviewCredentials.email,password:reviewCredentials.password}});return{api,storage}}
const future=()=>new Date(Date.now()+86400000).toISOString();
describe('parity client primitives',()=>{
 it.each([['100',3,['34','33','33']],['1001',2,['501','500']],['9000000000000000',1,['9000000000000000']]])('splits %s exactly',(total,count,expected)=>expect(splitMinor(total as string,count as number)).toEqual(expected));
 it('refuses zero-kobo shares and invalid participant counts',()=>{expect(()=>splitMinor('1',2)).toThrow();expect(()=>splitMinor('100',0)).toThrow();expect(()=>splitMinor('100',21)).toThrow()});
 it('makes WAT explicit rather than using browser timezone',()=>{expect(watISO('2026-09-23T08:30')).toBe('2026-09-23T07:30:00.000Z');expect(watInput(new Date('2026-09-23T07:30:00Z'))).toBe('2026-09-23T08:30');expect(localMonth(new Date('2026-08-31T23:30:00Z'))).toBe('2026-09')});
 it('round-trips binary WebAuthn fields without textual corruption',()=>{const bytes=new Uint8Array([0,255,254,128,65]).buffer;expect(new Uint8Array(decodeBase64URL(encodeBase64URL(bytes)))).toEqual(new Uint8Array(bytes))});
});
describe('synthetic parity journeys are separate from live acceptance',()=>{
 it('saves household bills and versioned reminders across review reload',async()=>{const{api,storage}=await setup();const bill=await api.request<{id:string}>('POST','/v1/saved-bills',{body:{label:'Home power',product_id:'review-electricity',customer_id:'SYNTHETIC-METER',amount_minor:'10000',favourite:true}});const rem=await api.request<{id:string}>('POST','/v1/reminders',{body:{title:'Power reminder',amount_minor:'10000',bill_id:bill.id,due_at:future(),cadence:'monthly'}});await api.request('PATCH',`/v1/reminders/${rem.id}`,{body:{status:'paused',version:1}});const reopened=new ReviewTransport(storage);expect((await reopened.request<SavedBill[]>('GET','/v1/saved-bills'))[0].label).toBe('Home power');expect((await reopened.request<Reminder[]>('GET','/v1/reminders'))[0].status).toBe('paused');await api.request('DELETE',`/v1/saved-bills/${bill.id}`);expect((await api.request<Reminder[]>('GET','/v1/reminders'))[0].status).toBe('cancelled')});
 it('performs an assigned partial request payment and recovers its original key',async()=>{const{api}=await setup();const rid='req_review_incoming_001';const q=await api.request<Quote>('POST',`/v1/money-requests/${rid}/quote`,{body:{amount_minor:'10000'}});const a=await api.request<Approval>('POST',`/v1/quotes/${q.id}/authorisations`,{body:{pin:'123456'}});const body={quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey='request-linked-idempotency';const pay=await api.request<Payment>('POST','/v1/payments',{body,idempotencyKey});await api.request('POST','/v1/payments',{body,idempotencyKey});const r=await api.request<RequestDetail>('GET',`/v1/money-requests/${rid}`);expect(r.shares[0].received_minor).toBe('10000');const found=await api.request<{found:boolean;payment:Payment}>('GET',`/v1/payments/lookup?idempotency_key=${idempotencyKey}&quote_id=${q.id}`);expect(found.payment.id).toBe(pay.id)});
 it('never creates real funding details or fabricates device authentication',async()=>{const{api}=await setup();const result=await api.request<{details:{synthetic:boolean;account_number:string}}>('POST','/v1/funding/account');expect(result.details.synthetic).toBe(true);expect(result.details.account_number).toContain('NOT-A-BANK');await expect(api.request('POST','/v1/passkeys/register/begin',{body:{}})).rejects.toMatchObject({status:503})});
 it('keeps budget exclusions separate from wallet balances',async()=>{const{api}=await setup();const wallet=await api.request<Wallet>('GET','/v1/wallet');const month=localMonth();await api.request('POST','/v1/budgets',{body:{month,category:'housing',amount_minor:'3000000'}});await api.request('PATCH','/v1/payments/pay_review_history_00/annotation',{body:{category:'housing',note:'My private note',excluded:true}});const insights=await api.request<Insights>('GET','/v1/insights?month='+month);expect(insights.excluded_minor).toBe('2500000');expect(insights.categories.find(x=>x.category==='housing')?.budget_minor).toBe('3000000');expect((await api.request<Wallet>('GET','/v1/wallet')).balance_minor).toBe(wallet.balance_minor)});
 it('requires dual synthetic mailbox proofs and revokes the old login',async()=>{const{api}=await setup();const change=await api.request<{id:string}>('POST','/v1/me/email-change',{body:{new_email:'changed@example.invalid',password:reviewCredentials.password}});await expect(api.request('POST',`/v1/me/email-change/${change.id}/verify`,{body:{old_code:'000000',new_code:'123456'}})).rejects.toMatchObject({status:401});await api.request('POST',`/v1/me/email-change/${change.id}/verify`,{body:{old_code:'123456',new_code:'123456'}});await expect(api.request('GET','/v1/wallet')).rejects.toMatchObject({status:401})});
 it('closes neither an account with funds nor an account with open issues',async()=>{const{api}=await setup();const status=await api.request<{can_close:boolean;open_cases:number}>('GET','/v1/me/closure');expect(status.can_close).toBe(false);expect(status.open_cases).toBeGreaterThan(0);await expect(api.request('POST','/v1/me/closure',{body:{password:reviewCredentials.password,reason:'Review'}})).rejects.toMatchObject({status:409})});
 it('freezes new outgoing instructions and records security state',async()=>{const{api}=await setup();await api.request('POST','/v1/me/freeze',{body:{password:reviewCredentials.password,frozen:true}});expect((await api.request<Controls>('GET','/v1/me/controls')).frozen).toBe(true);const q=await api.request<Quote>('POST','/v1/quotes',{body:{kind:'internal',recipient_id:reviewCredentials.recipient,amount_minor:'1000',currency:'NGN',narration:'Review'}});const a=await api.request<Approval>('POST',`/v1/quotes/${q.id}/authorisations`,{body:{pin:'123456'}});await expect(api.request('POST','/v1/payments',{body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'frozen-review-request'})).rejects.toMatchObject({status:403})});
});
