import { describe, expect, it } from 'vitest';
import { ReviewTransport, reviewCredentials } from '../src/review/transport';
import type { Approval, Payment, Quote, Wallet } from '../src/api/types';
class MemoryStorage implements Storage {
  map=new Map<string,string>();get length(){return this.map.size;} clear(){this.map.clear();} getItem(k:string){return this.map.get(k)??null;} key(i:number){return [...this.map.keys()][i]??null;}removeItem(k:string){this.map.delete(k);}setItem(k:string,v:string){this.map.set(k,v);}
}
async function fixture(){const storage=new MemoryStorage();const api=new ReviewTransport(storage);await api.request('POST','/v1/auth/login',{body:{email:reviewCredentials.email,password:reviewCredentials.password,client:'web',device:'test'}});return {api,storage};}
async function approved(api:ReviewTransport){const q=await api.request<Quote>('POST','/v1/quotes',{body:{kind:'internal',recipient_id:reviewCredentials.recipient,amount_minor:'10000',currency:'NGN',narration:'Synthetic test'}});const a=await api.request<Approval>('POST',`/v1/quotes/${q.id}/authorisations`,{body:{pin:reviewCredentials.pin}});return {q,a};}
describe('explicit synthetic review adapter',()=>{
 it('requires sign-in for customer information',async()=>{const api=new ReviewTransport(new MemoryStorage());await expect(api.request('GET','/v1/wallet')).rejects.toMatchObject({status:401});});
 it('rejects incorrect review credentials',async()=>{const api=new ReviewTransport(new MemoryStorage());await expect(api.request('POST','/v1/auth/login',{body:{email:reviewCredentials.email,password:'wrong'}})).rejects.toMatchObject({status:401});});
 it('creates exactly one synthetic effect for a repeated idempotency key',async()=>{const{api}=await fixture();const before=await api.request<Wallet>('GET','/v1/wallet');const{q,a}=await approved(api);const options={body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'test-original-key-01'};const p=await api.request<Payment>('POST','/v1/payments',options);const duplicate=await api.request<Payment>('POST','/v1/payments',options);expect(p.id).toBe(duplicate.id);const after=await api.request<Wallet>('GET','/v1/wallet');expect(BigInt(before.balance_minor)-BigInt(after.balance_minor)).toBe(BigInt(q.total_minor));});
 it('retains the accepted operation when a response is lost',async()=>{const{api}=await fixture();api.setScenario('unknown');const{q,a}=await approved(api);await expect(api.request('POST','/v1/payments',{body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'test-lost-response-01'})).rejects.toMatchObject({code:'network_unknown'});const list=await api.request<Payment[]>('GET','/v1/payments?limit=100');expect(list.some(x=>x.quote_id===q.id)).toBe(true);});
 it('does not debit a confirmed failed synthetic operation',async()=>{const{api}=await fixture();api.setScenario('failed');const before=await api.request<Wallet>('GET','/v1/wallet');const{q,a}=await approved(api);const p=await api.request<Payment>('POST','/v1/payments',{body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'test-failed-operation'});expect(p.status).toBe('failed');expect((await api.request<Wallet>('GET','/v1/wallet')).balance_minor).toBe(before.balance_minor);await expect(api.request('GET',`/v1/payments/${p.id}/receipt`)).rejects.toMatchObject({status:409});});
 it('keeps pending funds separate from book balance',async()=>{const{api}=await fixture();api.setScenario('pending');const{q,a}=await approved(api);const before=await api.request<Wallet>('GET','/v1/wallet');const p=await api.request<Payment>('POST','/v1/payments',{body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'test-pending-operation'});const after=await api.request<Wallet>('GET','/v1/wallet');expect(p.status).toBe('pending');expect(after.balance_minor).toBe(before.balance_minor);expect(BigInt(after.held_minor)-BigInt(before.held_minor)).toBe(BigInt(q.total_minor));});
 it('never fabricates an unsupported funding endpoint',async()=>{const{api}=await fixture();await expect(api.request('POST','/v1/funding/accounts',{body:{}})).rejects.toMatchObject({status:404});});
 it('does not persist PINs or passwords in its scenario state',async()=>{const{api,storage}=await fixture();await approved(api);const data=storage.getItem('qpf.synthetic-review.v1')||'';expect(data).not.toContain(reviewCredentials.password);expect(data).not.toContain('authorisation_token');expect(data).not.toContain('"pin":');});
 it('restores synthetic history in the same tab, not a server session',async()=>{const{api,storage}=await fixture();const{q,a}=await approved(api);const p=await api.request<Payment>('POST','/v1/payments',{body:{quote_id:q.id,authorisation_token:a.authorisation_token},idempotencyKey:'test-restorable-operation'});const next=new ReviewTransport(storage);expect((await next.request<Payment>('GET',`/v1/payments/${p.id}`)).id).toBe(p.id);});
});
