import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, ShieldCheck, UploadCloud } from 'lucide-react';
import { useAction,useApp,useResource } from '../state';
import type {CustomerCapabilities,Upload} from '../api/parity';
import {Button,Callout,Card,CopyButton,ErrorBox,Field,Loading} from './ui';
import {money,dateTime} from '../api/money';
export function CapabilitiesCard(){const r=useResource<CustomerCapabilities>('/v1/me/capabilities');return <Card title="Your account, clearly" action={<Link className="text-link" to="/security-centre">Manage limits</Link>}><ErrorBox error={r.error} retry={r.reload}/>{r.loading?<Loading/>:r.data&&<><div className="parity-stats"><div><small>Verification tier</small><strong>{r.data.tier}</strong></div><div><small>Per payment</small><strong>{money(r.data.controls.per_payment_minor)}</strong></div><div><small>Daily amount remaining</small><strong>{money(r.data.controls.daily_remaining_minor)}</strong></div></div><p className="fineprint">Limits reset at midnight {r.data.limit_day_timezone}. Current eligibility: {r.data.features.transfers.replaceAll('_',' ')}.</p>{r.data.tier<1&&<Link to="/verification" className="button primary">Continue verification</Link>}{r.data.controls.frozen&&<Callout tone="warning" title="Outgoing payments are frozen">Your personal freeze is active. You can still read your account and contact support.</Callout>}</>}</Card>}
export function ReauthFields({password,setPassword,mfa,setMfa}:{password:string;setPassword:(v:string)=>void;mfa:string;setMfa:(v:string)=>void}){const {user}=useApp();return <><Field label="Current password"><input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} maxLength={256}/></Field>{user?.mfa_enabled&&<Field label="Authenticator code"><input type="password" inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength={6} value={mfa} onChange={e=>setMfa(e.target.value)}/></Field>}</>}
export function UploadPanel({purpose,caseId='',onChange}:{purpose:'kyc'|'support';caseId?:string;onChange?:(uploads:Upload[])=>void}){
 const {client,toast}=useApp();const uploads=useResource<Upload[]>(`/v1/uploads?purpose=${purpose}${caseId?'&case_id='+encodeURIComponent(caseId):''}`);const a=useAction();const [file,setFile]=useState<File>();
 useEffect(()=>{if(uploads.data)onChange?.(uploads.data)},[uploads.data]);
 return <div className="upload-panel"><ErrorBox error={uploads.error} retry={uploads.reload}/><ErrorBox error={a.error}/><Field label={purpose==='kyc'?'Private identity document':'Private case attachment'} hint="JPEG, PNG or PDF, at most 5 MiB. API uploads are encrypted and scanned. The synthetic review keeps metadata only; never upload real documents in review mode."><input type="file" accept="image/jpeg,image/png,application/pdf" disabled={a.busy} onChange={e=>setFile(e.target.files?.[0])}/></Field><Button variant="secondary" disabled={!file} busy={a.busy} onClick={()=>void a.run(async()=>{if(!file||file.size>5*1024*1024)throw new Error('Choose a file up to five MiB.');const form=new FormData();form.set('file',file);form.set('purpose',purpose);if(caseId)form.set('case_id',caseId);await client.request('POST','/v1/uploads',{body:form});setFile(undefined);uploads.reload();toast('Private document accepted. Review its scan status.');})}><UploadCloud size={16}/>Upload privately</Button>{uploads.loading?<Loading/>:<ul className="parity-list">{uploads.data?.map(v=><li key={v.id}><div><strong>{v.name}</strong><small>{v.state==='local_unscanned'?'LOCAL TEST · not malware-scanned':v.state} · {Math.ceil(v.size/1024)} KB</small></div><Button variant="quiet" onClick={()=>void a.run(async()=>{const blob=await client.request<Blob>('GET',`/v1/uploads/${v.id}/download`,{raw:true});download(blob,v.name);})}>Download</Button>{purpose==='kyc'&&<Button variant="quiet" onClick={()=>void a.run(async()=>{await client.request('DELETE',`/v1/uploads/${v.id}`);uploads.reload();})}>Remove</Button>}</li>)}</ul>}</div>
}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ExactRecipient({onSelected}:{onSelected:(id:string,name:string)=>void}){const {client}=useApp();const a=useAction();const [handle,setHandle]=useState('');const [found,setFound]=useState<{id:string;name:string;handle:string}>();return <div><Field label="Qpay handle" hint="Exact opt-in handle only. We do not expose a searchable customer directory."><input value={handle} maxLength={25} placeholder="@theirhandle" onChange={e=>{setHandle(e.target.value);setFound(undefined);onSelected('','')}}/></Field><Button variant="secondary" busy={a.busy} disabled={handle.length<4} onClick={()=>void a.run(async()=>{const value=await client.request<{id:string;name:string;handle:string}>('GET',`/v1/recipients/lookup?handle=${encodeURIComponent(handle)}`);setFound(value);onSelected(value.id,value.name);})}>Find exact recipient</Button><ErrorBox error={a.error}/>{found&&<div className="verified-name"><CheckCircle2 size={18}/><strong>{found.name} · @{found.handle}</strong><small>Account display name; verify the intended person.</small></div>}</div>}
export function DataTime({value}:{value?:string}){return <small>{value?dateTime(value):'Not yet observed'}</small>}
export function ReviewGate({title,children}:{title:string;children:React.ReactNode}){return <Callout title={title}><ShieldCheck size={15}/>{children}</Callout>}
export {CopyButton};
