import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAction,useApp,useResource} from '../state';
import {categories} from '../api/parity';
import type {Payment} from '../api/types';
import {Button,Callout,Card,ErrorBox,Field,Form,Loading,Badge} from './ui';
import {dateTime,money} from '../api/money';
export function PaymentExtras({payment}:{payment:Payment}){const {client,toast}=useApp();const timeline=useResource<{events:{type:string;status?:string;at:string}[];hold_minor:string;hold_state:string;next_action:string}>(`/v1/payments/${payment.id}/timeline`);const annotation=useResource<{category:string;note:string;excluded:boolean}>(`/v1/payments/${payment.id}/annotation`);const a=useAction();const [category,setCategory]=useState('other'),[note,setNote]=useState(''),[excluded,setExcluded]=useState(false);useEffect(()=>{if(annotation.data){setCategory(annotation.data.category);setNote(annotation.data.note);setExcluded(annotation.data.excluded)}},[annotation.data]);return <><Card title="Original-payment timeline"><ErrorBox error={timeline.error} retry={timeline.reload}/>{timeline.loading?<Loading/>:timeline.data&&<><p>{timeline.data.hold_state?`${money(timeline.data.hold_minor)} hold · ${timeline.data.hold_state}`:'No external payment hold'}</p><ol className="event-timeline">{timeline.data.events.map((v,i)=><li key={i}><strong>{v.type.replaceAll('_',' ')}{v.status?' · '+v.status:''}</strong><small>{dateTime(v.at)}</small></li>)}</ol><Callout title="Next step">{timeline.data.next_action}</Callout></>}</Card><Card title="Your category & private note"><ErrorBox error={annotation.error} retry={annotation.reload}/><Form onSubmit={()=>void a.run(async()=>{await client.request('PATCH',`/v1/payments/${payment.id}/annotation`,{body:{category,note,excluded}});toast('Payment category and note saved.');})}><Field label="Spending category"><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Private payment note"><textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></Field><label className="checkbox"><input type="checkbox" checked={excluded} onChange={e=>setExcluded(e.target.checked)}/>Exclude from spending insights (not from the ledger)</label><ErrorBox error={a.error}/><Button variant="secondary" type="submit" busy={a.busy} disabled={annotation.loading}>Save payment note</Button></Form>{payment.direction==='outgoing'&&<Link className="button quiet" to={`${payment.kind==='bill'?'/bills/pay':'/transfers/new'}?type=${payment.kind}&repeat=${payment.id}`}>Prepare a new payment</Link>}</Card></>}
export function BillerAvailability({product}:{product:string}){const {client}=useApp();const r=useResource<{product_id:string;state:string;watching:boolean;observed_at?:string}[]>('/v1/bills/availability');const a=useAction();const item=r.data?.find(v=>v.product_id===product);return <div className="biller-availability"><small>Latest biller state: {item?.state||'unknown'}{item?.observed_at?' · '+dateTime(item.observed_at):''}. This is not a guarantee for the next purchase.</small><Button variant="quiet" disabled={!product} busy={a.busy} onClick={()=>void a.run(async()=>{await client.request('POST','/v1/bills/watch',{body:{product_id:product,watching:!item?.watching}});r.reload()})}>{item?.watching?'Stop availability alerts':'Notify me when available again'}</Button><ErrorBox error={a.error}/></div>}
