import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
const credentials=()=>JSON.parse(readFileSync(process.env.QPF_BROWSER_FIXTURE || '/tmp/qpf-web-fixture.json','utf8')) as {email:string,password:string,pin:string,recipient_id:string};
async function login(page:Page){const c=credentials();await page.goto('/login');await expect(page.getByRole('button',{name:'Fill sample sign-in'})).toHaveCount(0);await page.getByLabel('Email address').fill(c.email);await page.getByLabel('Password',{exact:true}).fill(c.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('.balance-card')).toBeVisible();}
async function send(page:Page){await page.getByRole('button',{name:'Continue to authorisation'}).click();await page.getByLabel('Transaction PIN',{exact:true}).fill(credentials().pin);await page.getByRole('button',{name:'Authorise payment'}).click();await expect(page).toHaveURL(/activity\/pay_/);await expect(page.locator('.transaction-detail').getByText('Completed',{exact:true})).toBeVisible({timeout:30000});}
test('real Go API cookies, CSRF, internal ledger transfer and receipt',async({page,context})=>{await login(page);const cookies=await context.cookies();expect(cookies.some(c=>c.name==='qpf_customer_access'&&c.httpOnly&&c.sameSite==='Strict')).toBe(true);expect(cookies.some(c=>c.name==='qpf_customer_refresh'&&c.httpOnly)).toBe(true);await page.reload();await expect(page.locator('.balance-card')).toBeVisible();await page.goto('/transfers/new?type=internal');await page.getByLabel('Recipient Qpay account ID').fill(credentials().recipient_id);await page.getByLabel('Amount (NGN)').fill('100.01');await page.getByLabel('Payment note').fill('Synthetic API browser internal transfer');await page.getByRole('button',{name:'Review transfer',exact:true}).click();await send(page);await page.getByRole('button',{name:'View receipt'}).click();await expect(page.locator('.receipt-sheet')).toContainText('local');const data=await page.evaluate(()=>Object.entries(sessionStorage));expect(JSON.stringify(data)).not.toContain('authorisation_token');expect(JSON.stringify(data)).not.toContain(credentials().password);});
test('real Go API bank enquiry, beneficiary, external worker simulator',async({page})=>{await login(page);await page.goto('/transfers/new');await page.getByRole('button',{name:'+ New recipient'}).click();await page.getByLabel('Bank',{exact:true}).selectOption('999');await page.getByLabel('Account number',{exact:true}).fill('1234567890');await page.getByRole('button',{name:'Check account name'}).click();await page.getByRole('button',{name:'Save and use recipient'}).click();await page.getByLabel('Amount (NGN)').fill('250.00');await page.getByLabel('Payment note').fill('Synthetic API bank transfer');await page.getByRole('button',{name:'Review transfer',exact:true}).click();await send(page);});
test('real Go API bill validation, payment and original fulfilment',async({page})=>{await login(page);await page.goto('/bills/pay?product=synthetic-electricity');await page.getByLabel('Customer / service identifier').fill('SYNTHETIC-METER');await page.getByLabel('Amount (NGN)').fill('500.00');await page.getByLabel('Payment note').fill('Synthetic API electricity');await page.getByRole('button',{name:'Validate bill & review'}).click();await send(page);await page.getByRole('button',{name:'Retrieve purchased value'}).click();await expect(page.locator('.token-value')).toContainText('SYNTHETIC');});
test('real Go API preferences, support conversation and statement',async({page})=>{await login(page);await page.goto('/settings/preferences');await page.getByRole('switch').first().check();await page.getByRole('button',{name:'Save preferences'}).click();await expect(page.locator('.toast')).toBeVisible();await page.reload();await expect(page.getByRole('switch').first()).toBeChecked();await page.goto('/support/new');await page.getByLabel('Subject').fill('Synthetic API browser review');await page.getByLabel('Message',{exact:true}).fill('Testing customer-owned case creation');await page.getByRole('button',{name:'Create support case'}).click();await expect(page).toHaveURL(/support\/case_/);await page.getByLabel('Reply to this case').fill('Synthetic browser follow-up');await page.getByRole('button',{name:'Send reply'}).click();await expect(page.getByText('Synthetic browser follow-up',{exact:true})).toBeVisible();await page.goto('/statements');await page.getByRole('button',{name:/Generate|View statement|Prepare statement/}).click();await expect(page.getByText('Opening balance',{exact:true})).toBeVisible();});
test('API outage never substitutes synthetic customer data',async({page})=>{await page.route('http://localhost:8080/**',route=>route.abort('failed'));await page.goto('/');await expect(page.getByRole('heading',{name:'Let’s reconnect.'})).toBeVisible();await expect(page.getByText('Amina Okoro',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Fill sample sign-in'})).toHaveCount(0);});
test('production capability blocks the review application’s payment submit',async({page})=>{await login(page);await page.route('http://localhost:8080/v1/capabilities',route=>route.fulfill({json:{data:{environment:'production',currency:'NGN',external_payments_configured:true,notifications:'off',synthetic_execution:false,growth_products_enabled:false,production_acceptance:false},request_id:'req_capability_test'}}));await page.reload();await page.goto('/transfers/new?type=internal');await expect(page.getByRole('button',{name:'Review transfer',exact:true})).toBeDisabled();await expect(page.getByText('Payment submission is unavailable',{exact:true})).toBeVisible();});
