import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

async function login(page:Page){await page.goto('/login');await page.getByRole('button',{name:'Fill sample sign-in'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Hello, Amina.'})).toBeVisible();}
async function internalQuote(page:Page){await page.goto('/transfers/new?type=internal');await page.getByLabel('Recipient Qpay account ID').fill('usr_review_tunde_02');await page.getByLabel('Amount (NGN)').fill('1000.00');await page.getByLabel('Payment note').fill('Synthetic acceptance test');await page.getByRole('button',{name:'Review transfer',exact:true}).click();await expect(page.getByRole('button',{name:'Continue to authorisation'})).toBeVisible();}
async function authorise(page:Page){await page.getByRole('button',{name:'Continue to authorisation'}).click();await page.getByLabel('Transaction PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Submit synthetic payment'}).click();}
async function scenario(page:Page,value:string){await page.goto('/review');await page.getByLabel('Next payment or request scenario').selectOption(value);}

test('authentication layouts exclude portal navigation and invalid login fails',async({page})=>{await page.goto('/login');await expect(page.locator('.sidebar')).toHaveCount(0);await page.getByLabel('Email address').fill('review@qpay.example.invalid');await page.getByLabel('Password',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page).toHaveURL(/\/login$/);});
test('register, verify and recover a synthetic account',async({page})=>{await page.goto('/register');await page.getByLabel('Full name').fill('Review Customer');await page.getByLabel('Email address').fill('new@example.invalid');await page.getByLabel('Create password',{exact:true}).fill('Synthetic-password-2026');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).click();await expect(page).toHaveURL(/verify-email/);await page.getByLabel('Verification code').fill('000000');await page.getByRole('button',{name:'Verify email',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.getByLabel('Verification code').fill('123456');await page.getByRole('button',{name:'Verify email',exact:true}).click();await expect(page).toHaveURL(/login/);await page.getByRole('link',{name:'Forgot password?'}).click();await expect(page).toHaveURL(/forgot-password/);await expect(page.getByRole('heading',{name:/get you back in/})).toBeVisible();await page.getByLabel('Email address').fill('new@example.invalid');await page.getByRole('button',{name:'Request recovery code'}).click();await expect(page).toHaveURL(/reset-password/);await page.getByLabel('Verification code').fill('123456');await page.getByLabel('New password',{exact:true}).fill('Changed-password-2026');await page.getByRole('button',{name:'Reset password',exact:true}).click();await expect(page).toHaveURL(/login/);});
test('internal payment, receipt, reload and no secret recovery persistence',async({page})=>{await login(page);await internalQuote(page);await authorise(page);await expect(page).toHaveURL(/activity\/pay_/);await expect(page.locator('.transaction-detail').getByText('Completed',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'View receipt'}).click();await expect(page.locator('.receipt-sheet')).toBeVisible();const receipt=page.waitForEvent('download');await page.getByRole('button',{name:'Download receipt JSON'}).click();expect((await receipt).suggestedFilename()).toBe('qpay-receipt.json');const stored=await page.evaluate(()=>sessionStorage.getItem('qpf.payment-recovery.v1'));expect(stored).toBeNull();});
test('bank name enquiry and explicit beneficiary save before transfer',async({page})=>{await login(page);await page.goto('/transfers/new');await page.getByRole('button',{name:'+ New recipient'}).click();await page.getByLabel('Bank',{exact:true}).selectOption('999');await page.getByLabel('Account number',{exact:true}).fill('1234567890');await page.getByRole('button',{name:'Check account name'}).click();await expect(page.locator('.verified-name')).toBeVisible();await page.getByLabel('Saved recipient label').fill('Synthetic bank recipient');await page.getByRole('button',{name:'Save and use recipient'}).click();await page.getByLabel('Amount (NGN)').fill('500.00');await page.getByLabel('Payment note').fill('Synthetic bank transfer');await page.getByRole('button',{name:'Review transfer',exact:true}).click();await authorise(page);await expect(page).toHaveURL(/activity\/pay_/);await expect(page.locator('.transaction-detail').getByText('Completed',{exact:true})).toBeVisible();});
test('bill validation, vend and protected fulfilment retrieval',async({page})=>{await login(page);await page.goto('/bills/pay?product=review-electricity');await page.getByLabel('Customer / service identifier').fill('SYNTHETIC-METER');await page.getByLabel('Amount (NGN)').fill('2000.00');await page.getByLabel('Payment note').fill('Synthetic electricity bill');await page.getByRole('button',{name:'Validate bill & review'}).click();await authorise(page);await expect(page).toHaveURL(/activity\/pay_/);await page.getByRole('button',{name:'Retrieve purchased value'}).click();await expect(page.locator('.token-value')).toContainText('SYNTHETIC');});
test('response loss recovers original payment without a second instruction',async({page})=>{await login(page);await scenario(page,'unknown');await internalQuote(page);await authorise(page);await expect(page).toHaveURL(/transfers\/recovery/);await expect(page.getByText('Do not submit a replacement',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Check original request'}).click();await expect(page).toHaveURL(/activity\/pay_/);await expect(page.locator('.transaction-detail').getByText('Completed',{exact:true})).toBeVisible();});
test('pending state does not issue a success receipt',async({page})=>{await login(page);await scenario(page,'pending');await internalQuote(page);await authorise(page);await expect(page).toHaveURL(/activity\/pay_/);await expect(page.locator('.transaction-detail').getByText('Pending',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'View receipt'})).toHaveCount(0);await expect(page.getByText('The original request is still being checked',{exact:true})).toBeVisible();});
test('confirmed failure is distinct from pending and has no success receipt',async({page})=>{await login(page);await scenario(page,'failed');await internalQuote(page);await authorise(page);await expect(page).toHaveURL(/activity\/pay_/);await expect(page.getByText('Confirmed unsuccessful',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'View receipt'})).toHaveCount(0);});
test('expired quote cannot advance to authorisation',async({page})=>{await login(page);await scenario(page,'expired');await internalQuote(page);await expect(page.getByRole('button',{name:'Continue to authorisation'})).toBeDisabled();await expect(page.getByText('This quote has expired.',{exact:true})).toBeVisible();});
test('wrong PIN does not submit and remains editable',async({page})=>{await login(page);await internalQuote(page);await page.getByRole('button',{name:'Continue to authorisation'}).click();await page.getByLabel('Transaction PIN',{exact:true}).fill('000000');await page.getByRole('button',{name:'Submit synthetic payment'}).click();await expect(page.getByRole('alert')).toBeVisible();await expect(page).toHaveURL(/transfers\/new/);});
test('funding remains synthetic and closure requires settled account',async({page})=>{await login(page);await page.goto('/funding');await page.getByRole('button',{name:'Request funding instructions'}).click();await expect(page.getByText('Synthetic test details — do not send money',{exact:true})).toBeVisible();await page.goto('/settings/privacy');await expect(page.getByRole('button',{name:'Review account closure'})).toBeDisabled();await expect(page.getByText('Resolve remaining items first',{exact:true})).toBeVisible();});
test('profile and communication preferences persist within the review tab',async({page})=>{await login(page);await page.goto('/settings/profile');await page.getByLabel('Display name',{exact:true}).fill('Amina Review');await page.getByRole('button',{name:/Save.*name|Save profile|Save changes/}).first().click();await expect(page.locator('.toast')).toBeVisible();await page.goto('/settings/preferences');await page.getByRole('switch').first().check();await page.getByRole('button',{name:'Save preferences'}).click();await expect(page.locator('.toast')).toContainText('Communication preferences saved.');await page.reload();await expect(page.getByRole('switch').first()).toBeChecked();});
test('support case creation and customer reply',async({page})=>{await login(page);await page.goto('/support/new');await page.getByLabel('Subject').fill('Synthetic case');await page.getByLabel('Message',{exact:true}).fill('A question for the review session');await page.getByRole('button',{name:'Create support case'}).first().click();await expect(page).toHaveURL(/support\/case_/);await page.getByLabel(/reply/i).fill('Synthetic follow-up');await page.getByRole('button',{name:/Send reply/}).click();await expect(page.getByText('Synthetic follow-up',{exact:true})).toBeVisible();});
test('statement download and manual UAT export',async({page})=>{await login(page);await page.goto('/statements');await page.getByRole('button',{name:/Generate|View statement|Prepare statement/}).click();await expect(page.getByText('Opening balance',{exact:true})).toBeVisible();const event=page.waitForEvent('download');await page.getByRole('button',{name:/Download CSV/}).click();expect((await event).suggestedFilename()).toContain('.csv');await page.goto('/review');await expect(page.getByLabel('Result for UAT-01')).toHaveValue('not-tested');await page.getByLabel('Result for UAT-01').selectOption('passed');const notes=page.waitForEvent('download');await page.getByRole('button',{name:'Export review notes'}).click();expect((await notes).suggestedFilename()).toBe('qpay-review-notes.json');});

test('screens, responsive layout, dark theme and accessibility evidence',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));mkdirSync('test-results/screenshots',{recursive:true});
 const captures:Record<string,unknown>[]=[];const source=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();
 const capture=async(name:string)=>{await page.waitForTimeout(300);const image=`test-results/screenshots/${name}.png`;await page.screenshot({path:image,fullPage:true});captures.push({path:image,screen:name,route:new URL(page.url()).pathname+new URL(page.url()).search,source_commit:source,captured_at:new Date().toISOString(),environment:'test',fixture_id:'qpf-review-v1',state:'synthetic-review',viewport:page.viewportSize(),sha256:createHash('sha256').update(readFileSync(image)).digest('hex')});writeFileSync('test-results/screenshots/provenance.json',JSON.stringify({schema_version:1,service:'WebApp',captures},null,2));const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();expect(audit.violations,`${name} accessibility`).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name} horizontal overflow`).toBe(true);};
 await page.goto('/login');await capture('login-desktop');await login(page);await capture('overview-desktop');
 for(const[path,name]of[['/transfers','transfers'],['/transfers/new','transfer-details'],['/bills','bills'],['/wallet','wallet'],['/activity','activity'],['/beneficiaries','beneficiaries'],['/statements','statements'],['/notifications','notifications'],['/settings/profile','profile'],['/settings/security','security'],['/settings/devices','devices'],['/settings/preferences','preferences'],['/settings/privacy','privacy'],['/verification','verification'],['/support','support'],['/support/new','support-new'],['/review','review-workspace'],['/bills/saved','saved-bills'],['/bills/tokens','tokens'],['/calendar','calendar'],['/calendar/schedule','schedule'],['/requests','requests'],['/insights','insights'],['/funding','funding'],['/security-centre','security-centre'],['/settings/contact','contact'],['/search','search']]){await page.goto(path);await capture(name);}
 await internalQuote(page);await capture('transfer-quote');await page.getByRole('button',{name:'Continue to authorisation'}).click();await capture('transfer-authorisation');await page.getByLabel('Transaction PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Submit synthetic payment'}).click();await expect(page).toHaveURL(/activity\/pay_/);await capture('transfer-result');await page.getByRole('button',{name:'View receipt'}).click();await capture('receipt');
 await page.goto('/');await page.getByRole('button',{name:'Switch to dark theme'}).click();await capture('overview-dark');await page.getByRole('button',{name:'Switch to light theme'}).click();await page.setViewportSize({width:390,height:844});await capture('overview-mobile');await page.getByRole('button',{name:'Open navigation'}).click();await capture('navigation-mobile');await page.locator('.sidebar').getByRole('link',{name:'Bill payments',exact:true}).click();await capture('bills-mobile');await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('.sidebar').getByRole('button',{name:'Sign out',exact:true}).click();await expect(page).toHaveURL(/login/);await capture('login-mobile');expect(errors).toEqual([]);
});

test('standalone offline review opens without API network access',async({page})=>{const external:string[]=[];page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await page.goto(pathToFileURL(resolve('dist/qpay-offline-review.html')).href);await expect(page.locator('.auth-layout')).toBeVisible();await page.getByRole('button',{name:'Fill sample sign-in'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Hello, Amina.'})).toBeVisible();expect(external).toEqual([]);});
