import {describe,it,expect,vi} from 'vitest';
import {AdminAPI,apiOrigin,APIError} from '../src/api';
const ok=(data:unknown)=>new Response(JSON.stringify({data}),{status:200,headers:{'Content-Type':'application/json'}});
const failure=(status:number,code='forbidden')=>new Response(JSON.stringify({error:{code,message:'Not permitted'},request_id:'request-fixture'}),{status});
const login={email:'admin@example.invalid',password:'synthetic-password',mfa_code:'123456',client:'web' as const,device:'test'};
describe('staff credential boundary',()=>{
 for(const origin of ['http://api.example.invalid','https://user:pass@api.example.invalid','https://api.example.invalid/path','https://api.example.invalid/?token=secret','https://api.example.invalid/#secret','ftp://api.example.invalid'])it('rejects unsafe origin '+origin,()=>expect(()=>apiOrigin(origin,true)).toThrow());
 it('allows explicit isolated local HTTP only',()=>{expect(()=>apiOrigin('http://localhost:8080',false)).toThrow();expect(apiOrigin('http://localhost:8080',true)).toBe('http://localhost:8080')});
 for(const path of ['/v1/me','//evil.invalid/v1/admin/a','/v1/admin/../auth','/v1/admin/\\test','/v1/admin/test#fragment'])it('rejects non-staff or unsafe path '+path,async()=>{const fetcher=vi.fn();const a=new AdminAPI('https://api.example.invalid',false,fetcher);await expect(a.request('GET',path)).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled()});
 it('uses staff cookies and memory-only CSRF, never bearer auth',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValueOnce(ok({csrf_token:'synthetic-csrf',user:{id:'staff'},mfa_enrolment_required:false})).mockResolvedValueOnce(ok({status:'recorded'}));const a=new AdminAPI('https://api.example.invalid',false,fetcher);await a.login(login);await a.request('POST','/v1/admin/console/actions',{action:'note'});const init=fetcher.mock.calls[1][1]!;expect(init.credentials).toBe('include');expect(init.redirect).toBe('error');expect(init.cache).toBe('no-store');expect(init.headers).toMatchObject({'X-CSRF-Token':'synthetic-csrf'});expect(init.headers).not.toHaveProperty('Authorization')});
 it('does not repeat an ambiguous staff mutation',async()=>{const fetcher=vi.fn().mockRejectedValue(new Error('Response lost'));const a=new AdminAPI('https://api.example.invalid',false,fetcher);await expect(a.request('POST','/v1/admin/console/actions',{action:'control_decide'})).rejects.toThrow('Response lost');expect(fetcher).toHaveBeenCalledTimes(1)});
 it('surfaces API code and support reference',async()=>{const a=new AdminAPI('https://api.example.invalid',false,vi.fn().mockResolvedValue(failure(403)));await expect(a.request('GET','/v1/admin/console/records/staff')).rejects.toMatchObject({status:403,code:'forbidden',requestId:'request-fixture'})});
 it('restores without rotating a valid session',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(ok({csrf_token:'csrf'})).mockResolvedValueOnce(ok({id:'staff',role:'admin'}));const a=new AdminAPI('https://api.example.invalid',false,fetcher);expect(await a.restore()).toMatchObject({id:'staff'});expect(fetcher).toHaveBeenCalledTimes(2)});
 it('rotates expired access once on restoration, using existing staff refresh cookie',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(ok({csrf_token:'old'})).mockResolvedValueOnce(failure(401)).mockResolvedValueOnce(ok({csrf_token:'new'})).mockResolvedValueOnce(ok({id:'staff'}));const a=new AdminAPI('https://api.example.invalid',false,fetcher);expect(await a.restore()).toMatchObject({id:'staff'});expect(fetcher.mock.calls[2][0]).toContain('/v1/admin/auth/refresh');expect(fetcher.mock.calls[2][1].headers).toMatchObject({'X-CSRF-Token':'old'});expect(fetcher).toHaveBeenCalledTimes(4)});
 it('does not hide network failures as logged-out success',async()=>{const a=new AdminAPI('https://api.example.invalid',false,vi.fn().mockRejectedValue(new Error('Network down')));await expect(a.restore()).rejects.toThrow('Network down')});
 it('accepts empty 204 and rejects malformed envelopes',async()=>{const a=new AdminAPI('https://api.example.invalid',false,vi.fn().mockResolvedValueOnce(new Response(null,{status:204})).mockResolvedValueOnce(ok(undefined)));expect(await a.request('DELETE','/v1/admin/auth/sessions/test')).toBeUndefined();await expect(a.request('GET','/v1/admin/auth/me')).rejects.toBeInstanceOf(APIError)});
});
