// Generated from registered Go routes. Do not edit.
export type APIPath =
"GET /v1/me/capabilities" |
"GET /v1/me/controls" |
"PATCH /v1/me/controls" |
"POST /v1/me/freeze" |
"POST /v1/auth/logout-all" |
"GET /v1/auth/history" |
"GET /v1/recipients/lookup" |
"GET /v1/payments/lookup" |
"GET /v1/payments/{id}/timeline" |
"GET /v1/payments/{id}/draft" |
"GET /v1/payments/{id}/annotation" |
"PATCH /v1/payments/{id}/annotation" |
"PATCH /v1/beneficiaries/{id}/favourite" |
"GET /v1/saved-bills" |
"POST /v1/saved-bills" |
"PATCH /v1/saved-bills/{id}" |
"DELETE /v1/saved-bills/{id}" |
"GET /v1/bills/token-archive" |
"GET /v1/bills/availability" |
"POST /v1/bills/watch" |
"GET /v1/reminders" |
"POST /v1/reminders" |
"PATCH /v1/reminders/{id}" |
"GET /v1/mandates" |
"POST /v1/mandates" |
"PATCH /v1/mandates/{id}" |
"GET /v1/mandates/{id}/history" |
"GET /v1/money-requests" |
"POST /v1/money-requests" |
"GET /v1/money-requests/{id}" |
"POST /v1/money-requests/{id}/action" |
"POST /v1/money-requests/{id}/quote" |
"GET /v1/insights" |
"GET /v1/insights/categories" |
"POST /v1/budgets" |
"DELETE /v1/budgets/{id}" |
"GET /v1/search" |
"GET /v1/funding/account" |
"POST /v1/funding/account" |
"GET /v1/identity/draft" |
"PATCH /v1/identity/draft" |
"POST /v1/identity/submit" |
"GET /v1/uploads" |
"POST /v1/uploads" |
"GET /v1/uploads/{id}/download" |
"GET /v1/admin/uploads/{id}/download" |
"DELETE /v1/uploads/{id}" |
"POST /v1/me/email-change" |
"POST /v1/me/email-change/{id}/verify" |
"GET /v1/me/closure" |
"POST /v1/me/closure" |
"POST /v1/me/export" |
"POST /v1/support/cases/{id}/escalate" |
"GET /v1/support/cases/{id}/timeline" |
"GET /v1/admin/identity/{id}" |
"POST /v1/admin/bills/availability" |
"POST /internal/funding/observations" |
"POST /v1/passkeys/register/begin" |
"POST /v1/passkeys/register/finish" |
"POST /v1/auth/passkeys/begin" |
"POST /v1/auth/passkeys/finish" |
"GET /v1/passkeys" |
"POST /v1/passkeys/{id}/revoke" |
"GET /health/live" |
"GET /health/ready" |
"GET /openapi.json" |
"GET /v1/capabilities" |
"POST /v1/auth/register" |
"POST /v1/auth/challenges" |
"POST /v1/auth/challenges/verify" |
"POST /v1/auth/login" |
"POST /v1/auth/refresh" |
"GET /v1/auth/csrf" |
"GET /v1/auth/me" |
"GET /v1/auth/sessions" |
"DELETE /v1/auth/sessions/{id}" |
"POST /v1/auth/logout" |
"POST /v1/auth/mfa/enrol" |
"POST /v1/auth/mfa/confirm" |
"POST /v1/auth/password" |
"POST /v1/auth/pin" |
"POST /v1/admin/auth/login" |
"POST /v1/admin/auth/refresh" |
"GET /v1/admin/auth/csrf" |
"GET /v1/admin/auth/me" |
"GET /v1/admin/auth/sessions" |
"DELETE /v1/admin/auth/sessions/{id}" |
"POST /v1/admin/auth/logout" |
"POST /v1/admin/auth/mfa/enrol" |
"POST /v1/admin/auth/mfa/confirm" |
"POST /v1/admin/auth/password" |
"GET /v1/me" |
"PATCH /v1/me" |
"GET /v1/wallet" |
"GET /v1/wallet/entries" |
"GET /v1/wallet/funding" |
"GET /v1/statements" |
"GET /v1/banks" |
"GET /v1/bills/products" |
"POST /v1/banks/enquiries" |
"POST /v1/bills/validations" |
"GET /v1/beneficiaries" |
"POST /v1/beneficiaries" |
"DELETE /v1/beneficiaries/{id}" |
"POST /v1/quotes" |
"GET /v1/quotes/{id}" |
"POST /v1/quotes/{id}/authorisations" |
"POST /v1/payments" |
"GET /v1/payments" |
"GET /v1/payments/{id}" |
"GET /v1/payments/{id}/receipt" |
"GET /v1/payments/{id}/fulfilment" |
"POST /v1/kyc/cases" |
"GET /v1/kyc/cases" |
"GET /v1/notifications" |
"POST /v1/notifications/{id}/read" |
"GET /v1/preferences" |
"PATCH /v1/preferences" |
"GET /v1/support/cases" |
"POST /v1/support/cases" |
"GET /v1/support/cases/{id}/messages" |
"POST /v1/support/cases/{id}/messages" |
"GET /v1/admin/support/cases" |
"GET /v1/admin/support/cases/{id}/messages" |
"POST /v1/admin/support/cases/{id}/messages" |
"GET /v1/admin/overview" |
"GET /v1/admin/customers" |
"POST /v1/admin/staff" |
"GET /v1/admin/kyc/cases" |
"GET /v1/admin/policy" |
"GET /v1/admin/proposals" |
"POST /v1/admin/proposals" |
"POST /v1/admin/proposals/{id}/decision" |
"GET /v1/admin/payments/{id}" |
"POST /v1/admin/payments/{id}/requery" |
"GET /v1/admin/audit" |
"POST /v1/admin/reconciliations" |
"GET /v1/admin/reconciliations" |
"POST /internal/notifications/authorise";
