import {useEffect,useId,useRef,useState} from 'react';
import type {ReactNode,FormEvent} from 'react';
import {Link} from 'react-router-dom';
import {AlertCircle,CheckCircle2,ChevronRight,LoaderCircle,X} from 'lucide-react';
import {APIError} from '../errors';
import {format,label} from '../modules';
import type {Row} from '../types';
export function useLoad<T>(key:string,load:()=>Promise<T>){
 const [tick,setTick]=useState(0);const [state,setState]=useState<{key:string;data?:T;error?:unknown;loading:boolean}>({key,loading:true});
 useEffect(()=>{let alive=true;setState({key,loading:true});load().then(data=>{if(alive)setState({key,data,loading:false})}).catch(error=>{if(alive)setState({key,error,loading:false})});return()=>{alive=false}},[key,tick]);
 return {...(state.key===key?state:{key,loading:true}),reload:()=>setTick(v=>v+1)};
}
export function ErrorBox({error}:{error:unknown}){if(!error)return null;return <div className="notice error" role="alert"><AlertCircle size={20}/><div><strong>{error instanceof APIError?error.message:error instanceof Error?error.message:'Unable to complete the request.'}</strong>{error instanceof APIError&&error.requestId&&<small>Support reference: {error.requestId}</small>}{error instanceof APIError&&error.code==='staff_step_up_required'&&<Link to="/security">Reauthenticate in the security centre, then inspect current state before retrying.</Link>}<small>No simulated success or automatic mutation retry has been used.</small></div></div>}
export function Notice({children,success=false}:{children:ReactNode;success?:boolean}){return <div className={'notice '+(success?'success':'info')} role="status">{success?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}<div>{children}</div></div>}
export function Loading(){return <div className="loading" role="status"><LoaderCircle className="spin" size={24}/> Loading authorised records…</div>}
export function Badge({value}:{value:unknown}){const s=String(value??'unknown');const tone=['active','approved','accepted','succeeded','ready','clean','resolved','available','completed'].includes(s)?'positive':['restricted','failed','dead','critical','rejected','declined','disabled','unavailable'].includes(s)?'negative':'neutral';return <span className={'badge '+tone}>{s.replaceAll('_',' ')}</span>}
export function PageTitle({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <header className="page-title"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1 tabIndex={-1}>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="actions">{children}</div>}</header>}
export function Empty({title='No records found',message='There are no matching records in the current environment.'}:{title?:string;message?:string}){return <div className="empty"><div className="empty-symbol">◇</div><h3>{title}</h3><p>{message}</p></div>}
export function DataTable({items,columns,resource,caption='Operational records'}:{items:Row[];columns:string[];resource?:string;caption?:string}){
 const [sort,setSort]=useState<{key:string;asc:boolean}|null>(null);
 if(!items.length)return <Empty/>;
 const sorted=[...items];if(sort)sorted.sort((a,b)=>{const aa=a[sort.key],bb=b[sort.key];let result;if(sort.key.endsWith('_minor')&&typeof aa==='string'&&typeof bb==='string'&& /^-?\d+$/.test(aa)&& /^-?\d+$/.test(bb))result=BigInt(aa)<BigInt(bb)?-1:BigInt(aa)>BigInt(bb)?1:0;else result=String(aa??'').localeCompare(String(bb??''),undefined,{numeric:true});return sort.asc?result:-result});
 return <div className="table-scroll" tabIndex={0} role="region" aria-label={caption}><table><caption className="sr-only">{caption}. Column sorting applies to this page only.</caption><thead><tr>{columns.map(c=><th key={c} scope="col" aria-sort={sort?.key===c?sort.asc?'ascending':'descending':'none'}><button className="sort" onClick={()=>setSort({key:c,asc:sort?.key===c?!sort.asc:true})}>{label(c)} <span aria-hidden="true">{sort?.key===c?(sort.asc?'↑':'↓'):'↕'}</span></button></th>)}{resource&&<th scope="col"><span className="sr-only">Open record</span></th>}</tr></thead><tbody>{sorted.map((row,index)=><tr key={String(row.id??index)}>{columns.map((c,i)=><td key={c} className={c.endsWith('_minor')?'money-cell':''}>{c==='status'?<Badge value={row[c]}/>:i===0&&resource?<Link className="record-link" to={'/records/'+resource+'/'+encodeURIComponent(String(row.id))}>{format(c,row[c])}</Link>:<span className={c.endsWith('_id')?'mono':''}>{format(c,row[c])}</span>}</td>)}{resource&&<td><Link className="icon-button" aria-label={'Open '+String(row.id)} to={'/records/'+resource+'/'+encodeURIComponent(String(row.id))}><ChevronRight size={18}/></Link></td>}</tr>)}</tbody></table></div>
}
export function Facts({record,omit=[]}:{record:Row;omit?:string[]}){return <dl className="facts">{Object.entries(record).filter(([key])=>!omit.includes(key)).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{key==='status'?<Badge value={value}/>:typeof value==='object'&&value!==null?<pre>{JSON.stringify(value,null,2)}</pre>:format(key,value)}</dd></div>)}</dl>}
export function Field({label:caption,name,type='text',defaultValue='',required=true,options,help,min,max,placeholder}:{label:string;name:string;type?:string;defaultValue?:string;required?:boolean;options?:[string,string][];help?:string;min?:number;max?:number;placeholder?:string}){
 const id=useId();return <div className="field"><label htmlFor={id}>{caption}{required&&<span className="required" aria-hidden="true"> *</span>}</label>{options?<select id={id} name={name} defaultValue={defaultValue} required={required} aria-describedby={help?id+'-help':undefined}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select>:type==='textarea'?<textarea id={id} name={name} defaultValue={defaultValue} required={required} maxLength={max||1000} minLength={min} rows={4} placeholder={placeholder}/>:<input id={id} type={type} name={name} defaultValue={defaultValue} required={required} min={min} max={max} maxLength={['text','password','email'].includes(type)?max||500:undefined} autoComplete={type==='password'?'current-password':type==='email'?'email':'off'} placeholder={placeholder} aria-describedby={help?id+'-help':undefined}/>} {help&&<small id={id+'-help'}>{help}</small>}</div>
}
export function Form({onSubmit,children,submit='Save changes',danger=false}:{onSubmit:(data:FormData)=>Promise<unknown>;children:ReactNode;submit?:string;danger?:boolean}){const [busy,setBusy]=useState(false),[error,setError]=useState<unknown>(),[success,setSuccess]=useState(false);async function go(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const data=new FormData(e.currentTarget);setBusy(true);setError(undefined);setSuccess(false);try{await onSubmit(data);setSuccess(true)}catch(e){setError(e)}finally{setBusy(false)}}return <form onSubmit={go} className="form"><fieldset disabled={busy}>{children}</fieldset><ErrorBox error={error}/>{success&&<Notice success>Request completed. Refresh the relevant record to review the authoritative state.</Notice>}<button className={danger?'button danger':'button primary'} type="submit" disabled={busy}>{busy?<><LoaderCircle size={16} className="spin"/>Submitting…</>:submit}</button></form>}
export const text=(data:FormData,key:string)=>String(data.get(key)||'').trim();
export function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{const prior=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{ref.current?.close();prior?.focus()}},[]);return <dialog ref={ref} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose()}}><div className="dialog-heading"><h2 id={id}>{title}</h2><button aria-label="Close dialog" className="icon-button" onClick={onClose}><X/></button></div>{children}</dialog>}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
